### ISSUE TITLE
zafira response during huge load is too slow... think about increasing default timeout

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1008]
02:53:56 09:53:47.669 [main] ERROR com.qaprosoft.zafira.client.ZafiraClient - Unable to create user
02:53:56 com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
02:53:56 	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.qaprosoft.zafira.client.ZafiraClient.refreshToken(ZafiraClient.java:163) ~[zafira-client-3.0.42.jar:na]
02:53:56 	at com.qaprosoft.zafira.listener.ZafiraListener.initializeZafira(ZafiraListener.java:611) [zafira-client-3.0.42.jar:na]
02:53:56 	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:123) [zafira-client-3.0.42.jar:na]
02:53:56 	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:199) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.SuiteRunner.run(SuiteRunner.java:252) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.8.jar:na]
02:53:56 	at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.8.jar:na]
02:53:56 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295) [surefire-testng-2.18.jar:2.18]
02:53:56 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84) [surefire-testng-2.18.jar:2.18]
02:53:56 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90) [surefire-testng-2.18.jar:2.18]
02:53:56 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.jar:2.18]
02:53:56 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.jar:2.18]
02:53:56 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.jar:2.18]
02:53:56 Caused by: java.net.SocketTimeoutException: Read timed out
02:53:56 	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_181]
02:53:56 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_181]
02:53:56 	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_181]
02:53:56 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_181]
02:53:56 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_181]
02:53:56 	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_181]
02:53:56 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_181]
02:53:56 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_181]
02:53:56 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_181]
02:53:56 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_181]
02:53:56 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_181]
02:53:56 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_181]
02:53:56 	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[na:1.8.0_181]
02:53:56 	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_181]
02:53:56 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:1.8.0_181]
02:53:56 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_181]
02:53:56 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_181]
02:53:56 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) ~[na:1.8.0_181]
02:53:56 	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153) ~[jersey-client-1.19.4.jar:1.19.4]
02:53:56 	... 20 common frames omitted

**Comment by hursevich** [comment]
Default client timeout is 30 seconds, looks like we should not increase that one. According to our planned migration to Cloud solution with clustered webservice and db we should not face that anymore.
