### ISSUE TITLE
Incorrect primary and secondary owners are displayed on test runs

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#1022]
qps-auto user is marked as the owner for all tests instead of an appropriate primary and secondary ones 
<img width="462" alt="androidowners" src="https://user-images.githubusercontent.com/21850997/45899109-a009f380-bde4-11e8-8eeb-d85b9293d944.png">
<img width="444" alt="iosowners" src="https://user-images.githubusercontent.com/21850997/45899110-a0a28a00-bde4-11e8-9da5-4935b9d50eae.png">

**Comment by Boniara** [comment]
@rzubkouski , could you please share more information with us
