### ISSUE TITLE
Can't add filter

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#1028]
server v.multitenancy | client v.3.0.44

As a user I wan't to have a possibility to quick to sort test runs in order to see only todays (or at least those runs that took place in last 24 hours). For that purpose i create filter as displayed below. But it gives me nothing.

To be noted: there're few test runs that happened today

![screen shot 2018-09-21 at 6 56 18 pm](https://user-images.githubusercontent.com/18280686/45949909-39fcb680-c006-11e8-9a2f-7d10efe4de7f.png)

**Comment by Litsvin** [comment]
also, why I can't switch between various filters if one of them is applied? To do that i need to reset filters

**Comment by Boniara** [comment]
done
