### ISSUE TITLE
Unable to download android builds in the latest Zafira versions

### ISSUE THREAD

**Issue by rkatuzhanets** [qaprosoft/zafira#1051]
The possibility of downloading required android packages after migration to the latest versions of zafira disappeared.

**Comment by vdelendik** [comment]
@rzubkouski , @maksimsarychau try to register apk as test artifact. It should provide you ability to upload it to AWS s3 with valid access later manually

**Comment by vdelendik** [comment]
as only https://github.com/qaprosoft/carina/issues/703 is fixed we can try to do the same for downloaded builds to make them sharable via S3 bucket

**Comment by lmikhadyuk** [comment]
https://github.com/qaprosoft/carina/issues/850
