### ISSUE TITLE
Profile screen: color schema radio buttons under preferences section aren't aligned vertically on mobile devices

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#1053]
'Dark color schema' option button is a little bit shifted in comparison with 'Light color schema' button on mobile device
![preferences](https://user-images.githubusercontent.com/21850997/46136744-fba70780-c250-11e8-8427-fe45c09a61b9.png)

**Comment by Boniara** [comment]
will be fixed on redesign release
