### ISSUE TITLE
Screenshots should be downloaded to local machine

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#1102]
to organize screenshots comparison using baseline images ZafiraClient should be able not only upload but download images as well.

**Comment by Boniara** [comment]
Get images by ciTestRunId, ciTestId: 

Insert into elasticsearch.service.js
        var getObj = {
            '6d87c5d6-cdc3-4517-aa8e-4b3304e756f7': [
                "022f05a7-9e05-424b-9921-8d29b7862a64",
                "e48cad54-5789-4407-8e75-19cb5afa5ff4",
                "b00885c0-239a-413b-843d-f9f67f9abab0",
                "42fddb55-32c0-42b1-964e-a9c5b3f985f2",
                "6dbaa757-ae4d-4224-b704-2ffc28e18efc",
                "fc3e98eb-8853-427f-bf14-aeefca16626a",
                "4a45a352-014d-494e-a245-c8493aca573d",
                "d80c7d3f-3aa6-4c69-9b7c-6a767a9e4d59",
                "776dfdea-711a-461c-bc2c-81bc06f9b176",
                "3bdfeda9-911c-4084-b36a-94f8e2e245bc"
            ],
            '1e205197-d555-4050-b759-62dba615aa84': [
                "aca3ff6f-e8c1-4c30-be04-92178aea8597",
                "c3aec9ab-da8e-4cb5-abaa-29e5f068027e",
                "ad5d2a68-c9ca-4b37-9844-a6c1cd966586",
                "50cb6d3a-f0f6-4ac1-a83c-6d55cdd1d922",
                "b0a64330-1b45-4d93-b1c4-bc444712ad37",
                "8aad367f-1a87-4c81-b586-186440e1a5fe",
                "c1df373c-b66a-4216-8270-7e90160e3a18",
                "eceb8308-d510-4220-861d-fba67c9b787d",
                "e454fd0f-3c24-4141-af3c-c605c4424958",
                "865122e5-cee6-4396-8ef6-58e557ebb5c2"
            ]
        };


        var results = {};
        angular.forEach(getObj, function (testIds, testRunId, object) {
            testIds.forEach(function (testId) {
                get(testRunId, testId).then(function (rs) {
                    results[testRunId] = results[testRunId] ? results[testRunId] : {};
                    results[testRunId][testId] = results[testRunId][testId] ? results[testRunId][testId] : [];
                    results[testRunId][testId] = rs;
                    if(Object.size(results) == Object.size(getObj)) {
                        var size = Object.size(results[testRunId]);
                        if(getObj[testRunId].length == Object.size(results[testRunId])) {
                            angular.forEach(results, function (tests, testRun, object) {
                                console.log('TEST RUN CI RUN ID : ' + testRun);
                                angular.forEach(tests, function (images, t, o) {
                                    console.log('    TEST CI RUN ID : ' + t);
                                    images.forEach(function (image) {
                                        console.log('               ' + image);
                                    });
                                })
                            });
                        }
                    }
                });
            });
        });

        function get(testRunId, testId) {
            return $q(function (resolve, reject) {
                var instance = createInstance('https://readall:c3lpqobq@app.qaprosoft.cloud/elasticsearch');
                instance.search({
                        index: 'logs-2018.10.11, logs-2018.10.08',
                        size: 10000,
                        from: 0,
                        body: {
                            "sort":[
                                {
                                    "@timestamp":{
                                        "order":"asc"
                                    }
                                }
                            ],
                            "query":{
                                "bool":{
                                    "must":[
                                        {
                                            "term":{
                                                "correlation-id": testRunId + '_' + testId
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                    , function (er, rs) {
                        if(rs && rs.hits && rs.hits.hits) {
                            var result = [];
                            rs.hits.hits.forEach(function (hit) {
                                if(hit._source.headers && hit._source.headers['AMAZON_PATH']) {
                                    result.push(hit._source.headers['AMAZON_PATH']);
                                }
                            });
                            resolve(result);
                        }
                    });
            });
        };
