### ISSUE TITLE
optimize_execution mode is requested

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1108]
during the test automation the main purpose: provide as quick as possible test results.
For now as we split test results between different test suites, launch them in different envs etc we don't see how can we speedup this process using already populated data in Zafira.
How about optimize_execution mode which means that we don't even start the test which was executed on the same env/build... 
Ideally if optimize_execution is enabled we should preliminary analyze, maybe the same env/build etc was already tested and tested successfully. As only we find such use-case we can just provide link in Zafira onto the already passed test and do not execute current test case.
That's allow to minimize re-executions already tested cases and speedup test results deliver to the customers

**Comment by hursevich** [comment]
Logic looks pretty complicated, it is a bad idea to link results from different test runs. They may be executed on different dev builds and provide different results.
