### ISSUE TITLE
back button from test has strange "skip" item determination

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1121]
1) expand test run
2) open test info via "eye" icon
3) press back
-> test which was opened is marked as skip for several seconds and later is updated to valid status

**Comment by vdelendik** [comment]
seems like it is expected behavior to highlight test we reviewed. How about rectangle around test? Like slack/webex do when you start sharing display... just colored rectangle around

**Comment by Boniara** [comment]
is not a bug
