### ISSUE TITLE
NPE prevent test results publishing to zafira

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1155]
00:12:38 07:12:34.950 [main] ERROR com.qaprosoft.zafira.listener.ZafiraListener - Undefined error during test run registration!
00:12:38 java.lang.NullPointerException: null
00:12:38 	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:174) ~[zafira-client-3.3.46.jar:na]
00:12:38 	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:199) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.SuiteRunner.run(SuiteRunner.java:252) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.8.jar:na]
00:12:38 	at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.8.jar:na]
00:12:38 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295) [surefire-testng-2.18.jar:2.18]
00:12:38 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84) [surefire-testng-2.18.jar:2.18]
00:12:38 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90) [surefire-testng-2.18.jar:2.18]
00:12:38 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.jar:2.18]
00:12:38 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.jar:2.18]
00:12:38 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.jar:2.18]

**Comment by hursevich** [comment]
Unable to catch NPE in provided line of source code.
