### ISSUE TITLE
It will be useful to have TestRail integration in Zafira

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1160]
In such cases, Manual team can check actual Test Cases steps directly in Zafira and compare with logs and results. 
Also, it will be useful to store changes in Test Cases from TestRail to show automation team which tests should be reviewed and updated.  
TestRail Ids can be parsed from implemented cases. Same with test rail suites.

**Comment by maksimsarychau** [comment]
It can be additional Widget in our video and logs\screenshot page.
1). If we have TestRail integration - this widget should present
2). It there is a possibility to connect to the TestRail we should try to get TestRail SuiteID and TestRail ID for this test (Carina already provide such info based by @TestRailId tag, etc)
And having these suiteId and TestId parameters collect following fields from TestRail: Title, Preconditions, Steps, Expected Result and optionally - Section.
3). Save this info in Zafira DB with an association for current Test. 
4). If there is no possibility to connect to the TestRail (VPN issues, etc) - try to get test case details from Zafira DB. And if it is empty - show nothing.

**Comment by vdelendik** [comment]
let's reorganize in such way:
1) update testrail updater to be able to register all suite/testcase id values...
2) in test info view just provide link to testrail testsuite/testcase

or think about possibility to reuse tags but it is not a good solution for UI/Design

**Comment by hursevich** [comment]
Test rail tags are already there.
