### ISSUE TITLE
Design for test tags

### ISSUE THREAD

**Issue by akhursevich** [qaprosoft/zafira#1163]
Now they are looking like that:
<img width="1388" alt="screen shot 2018-11-02 at 4 24 16 pm" src="https://user-images.githubusercontent.com/1182755/47917845-d6df2900-debb-11e8-8aaf-c6d5eb9fdde5.png">
Find more suitable way to display test tags.

**Comment by vabramova** [comment]
zpl://screen?sid=5c3470a30e850fbe6663a823&pid=5acb41c5487a27ab9f0560a1
https://app.zeplin.io/project/5acb41c5487a27ab9f0560a1/screen/5c3470a30e850fbe6663a823
