### ISSUE TITLE
Add possibility to Add Filter in Zafira based on Priority and by any tag pair

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1166]
It will be useful to use a filter based on Test Priorities and based on any required tag name = value pair. 

![image](https://user-images.githubusercontent.com/4455896/47939020-25a1b880-dee6-11e8-8692-8ed0bb4d6211.png)

**Comment by hursevich** [comment]
Tags and priorities are filtering tests in context of test run, stored filters are applied for searching test runs. We are not capable to combine both search contexts.
