### ISSUE TITLE
String with passed, failed and skipped tests disappears after marking one test as passed

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#1169]
Environment: Win7, Chrome 70.0.3538.77

Steps:
1. Open any zafira test run with failed/skipped tests
2. Swipe on failed/skipped test
3. Mark as passed
Actual result: String with passed, failed and skipped tests disappears
Expected result: String with passed, failed and skipped tests should update with actual value of passed, failed, skipped tests

DEMO: https://www.dropbox.com/s/x01j5i1soq85dq9/ice_video_20181105-162342.webm?dl=0

**Comment by hursevich** [comment]
Not repro
