### ISSUE TITLE
Add ability to view result ( last 10 days or last 10 results ) for specific method. 

### ISSUE THREAD

**Issue by ydaroshka** [qaprosoft/zafira#1201]
Can we add an ability to see results of specific method(test case) in last 10 day or last 10 results of selected method. That's will help to determine  faster when  issue (bug) has been appeared and in this case  user don't need to open each test run to search for selected method.

**Comment by vdelendik** [comment]
@ydaroshka in new zafira starting from 3.4.51+ you should be able to open stability view much faster.
For now it has consolidated information about testcase pass rate on monthly basis. Please reopen if needed exactly 10 latest runs/days in additions
