### ISSUE TITLE
Personal dashboards — 'UPDATED' date information is displayed in timestamp format

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#1214]
It would be nice to display such kind of information like dates in human readable format instead of timestamp format.
<img width="1339" alt="dateformat" src="https://user-images.githubusercontent.com/21850997/48775266-9a923200-ecdd-11e8-80e1-122289a5a8ea.png">

**Comment by maksimsarychau** [comment]
As a temporary solution we can use TO_CHAR(Updated :: DATE, 'yyyy-mm-dd') with required date format

**Comment by hursevich** [comment]
Better to use convert logic like that: some_field::text
