### ISSUE TITLE
Unable to register multiply classes results in case of adding ZafiraListener as class annotation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1215]
Steps:
1) declare on classes level below annotation
@Listeners({ ZafiraListener.class })
2) combine into the single suite several test classes
3) run testNG suite
-> as result only first class is registered in Zafira

root cause:
zafira listener class and "initialized" property is calculated onStart(suite) for the 1st class.
2nd and other classes have new ZafiraListener instance with disabled integration by default

I recommend to override onStart(itestContext context) and reinit integration part inside this block as well.
it guarantees that all classes inside suite can be registered successfully

**Comment by hursevich** [comment]
Client documentation updated, the listener should be included into testng xml or pom xml.
