### ISSUE TITLE
Emailed (pdf) linechart UI is differ from original

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#1216]
Environment: Win7, Chrome 70.0.3538.102 (Official Build) (32-bit)

preconditions: 
Dashboard with linechart "Last 30 day's results".
The linechart contains data.

Steps:
1. Send dashboard via email
2. Open email with sent dashboard / Open dashboard pdf file
Actual result: linechart UI is differ from original (see screenshot)
Expected result: Linechart in pdf file should be as in dashboard web view

![web_view](https://user-images.githubusercontent.com/24683436/49041234-b7df6880-f1d5-11e8-9da3-b6e8d6c3e7ba.png)
![pdf_view](https://user-images.githubusercontent.com/24683436/49041275-cd549280-f1d5-11e8-9a86-5b0c146e0997.png)

**Comment by hursevich** [comment]
We have migrated to new Echarts library that does not that problem when sending by email. Looks like you tested on deprecated dashboards.
