### ISSUE TITLE
investigate possibility to bind websockets to new echarts

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1228]
new library allows to generate a lot of reports including reactive charts. It makes sense to setup set of rules howto bind and listen 1-2 common zafira websockets and convert data on the fly.
For example gauge charts are useful when we display data based on per second analysis and not per minute

**Comment by hursevich** [comment]
This is tricky to handle, not sure that a lot of users are staring at charts for a long period of time. Simple refresh should be good enough.
