### ISSUE TITLE
Download in zip gives you empty result

### ISSUE THREAD

**Issue by NadiMarkava** [qaprosoft/zafira#1235]
Steps

1. Click on "eye" on the right from failed test
2. You are on "Visuals" , that has down arrow
3. Click on down arrow
4. Downloading process is finished, and you can see zip file in your folder

Expected result : All screenshots are there 
Actual : Folder is empty

**Comment by vdelendik** [comment]
moreover even saving operation for the single screenshot doesn't work:
Access to XMLHttpRequest at 'https://.../artifacts/screenshots/01-24-2019/CX0zHCe1vfzCJawC3Qnd.png?X-Amz-Algorithm=AWS4-' from origin 'https://....cloud' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
