### ISSUE TITLE
Impossible to navigate back from test info direct url to test run page

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1238]
Often we should show direct URL to the exact test results (ending like tests/runs/7643/info/254313) and there is no trivial possibility just to go back to the Test Run (tests/runs/7643) by some button to for example change test status from Failed to Passed or just for adding bug. Or at least to check executed suite name. 

Can we add some button >> for this?

**Comment by hursevich** [comment]
This logic is refactored and now it is working in accordance with your expiration.
