### ISSUE TITLE
Add possibility to check TestRail title and steps\expected results on Test Info page

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1239]
After a long discussion with our customers, it was recognized that the main issue with low Zafira usage by customer' manual team and management - an impossibility for easily checking for executed test its TestRail title(s) and steps with expected results. 

Since now Zafira already knows all TestRail required info (projectId, suiteId, caseId) for each marked and executed test it is possible easily generate an URL to the Testrail and getting required info by adding Integration with TestRail in Zafira. 
In the integration part, we should configure TestRail URL and credentials. 
And if we have mapped Testrail case - we can show steps in additional div on the Zafira Test info page.

**Comment by vdelendik** [comment]
testrail cases id are visible now. this ticket let's use to create valid TestRail viewer as we have plain/group

**Comment by nsidorevich** [comment]
Duplicates #1284
