### ISSUE TITLE
schedule automatic materialized views update 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1241]
TOTAL_VIEW and THIRTY_DAYS_VIEW should be refreshed automatically.
schedule:
once per month:
SELECT cron.schedule ('0 0 1 * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY ZAFIRA.TOTAL_VIEW$$);

once per day:
SELECT cron.schedule ('0 7 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY ZAFIRA.THIRTY_DAYS_VIEW$$);

**Comment by hursevich** [comment]
Managed to integrated postgres cron trigger to the latest Kubernetes deployment.
