### ISSUE TITLE
Percentage string of passed tests overlaps block with piechart colors' definitions

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#1268]
Environment: Win7, Chrome 71.0.3578.98 (Official Build) (32-bit)

Descriptions: 
Strings with passed tests percentage overlaps block with piechart colors definitions (see screenshot)

![ice_screenshot_20190102-200752](https://user-images.githubusercontent.com/24683436/50603379-62c8fd80-0ecb-11e9-8642-d32108912e9b.png)

**Comment by hursevich** [comment]
@vdelendik insisted on such labels position. In general, we use screens with higher resolutions with wider areas for those charts.
