### ISSUE TITLE
Better support for k8s deployments

### ISSUE THREAD

**Issue by chadasapp** [qaprosoft/zafira#1270]
Hi. So I've been trying to get zafira deployed on k8s and while it's possible, there's a couple of gotchas that aren't immediately obvious when migrating from docker-compose.

1) You need to write an ingress controller -- this is pretty easy
2) The configuration files that are mounted as volumes do not work.

The latter is what I'd like to address in this task. As it stands, if you spin up a pod for say `qaprosoft/postgres:9.6`, it ends up being ill-provisioned since `/docker-entrypoint-initdb.d` is nowhere to be found. The two workarounds I found are either (A) mount it as a persistent volume, copy the files in, then terminate/recreate the pod or (B) create my own Dockerfile, copy the files in, then deploy from that. The former is manual, unintuitive and leaves no audit trail of changes, the latter creates a significant maintenance overhead for the operations team as that's 4 new images to maintain (db, rabbitmq, elasticsearch, logstash).

I'd love to discuss possible improvements we can see here.

**Comment by hursevich** [comment]
Hello, @chadasapp 
I'm sorry for long delay, for Kubernetes deployments we do not use this image directly. We highly recommend using KubeDB (https://kubedb.com/docs/0.9.0/guides/postgres/) as far as it simplifies to deploy production-ready DB replication.
I'm providing the detailed configuration in archive below:
[02_postgres.zip](https://github.com/qaprosoft/zafira/files/2794806/02_postgres.zip)
Feel free to ask if you have any question!

**Comment by chadasapp** [comment]
I ended up wrangling it into working :)

I'll double check that my manifests don't contain any private info I can't disclose--if they don't, I'd be more than happy to share them with upstream so your other users can benefit as well. I can't imagine I'm the only one who's deploying to k8s :)
