### ISSUE TITLE
Implement widgets wizard functionality for user.

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/zafira#1275]
I'd like to create new widgets based on widget templates being able to customize parameters and chart legend.

![wizard_step 2 - set a filter](https://user-images.githubusercontent.com/1182755/50822185-199d0180-1342-11e9-8be0-e612d1a5b3b0.png)
![wizard_step 1 - choose template](https://user-images.githubusercontent.com/1182755/50822186-199d0180-1342-11e9-8a64-aaff5e800d1d.png)

**Comment by Boniara** [comment]
was implemented
