### ISSUE TITLE
Window with TestCase-id is shown above list of test cases to the top of the page

### ISSUE THREAD

**Issue by andrey-sadchenko** [qaprosoft/zafira#1287]
**Steps:**
1. Open Zafira
2. Open test run results
3. Click on [clip] to see id test case - window with TestCase-id is shown
4. Scroll page down

**Expected result:**
Page can be scrolled down without any UI issues

**Actual result:** 
Window with TestCase-id is shown above list of test cases to the top of the page 

**Screenshot and video:**
https://www.dropbox.com/s/yrc7dagqj3c5ksy/zaf.png?dl=0
https://www.dropbox.com/s/qcsvzwb0jyt39c6/zaf.mov?dl=0

**Comment by danymill** [comment]
fixed
