### ISSUE TITLE
Long email address is not fully displayed on send by email screen

### ISSUE THREAD

**Issue by Annett14** [qaprosoft/zafira#1289]
Environment: Win'10, Chrome 71.0.3578.98, 64 bit
Zafira environment: stage
Steps:
1. Open any dashboard
2. Click Send by email button 
3. Enter a long email on a send by email screen
Actual result: long email address (more than 18-20 characters) is not fully displayed
Expected result: long email address is fully displayed

[Video](https://www.dropbox.com/s/e5ogw41uubbzz66/ice_video_20190116-232618.webm?dl=0)

**Comment by hursevich** [comment]
This is not an issue, when you press enter - email is fully displayed. This is the standard behavior of material library.
