### ISSUE TITLE
Create button becomes active before entering SQL query 

### ISSUE THREAD

**Issue by Annett14** [qaprosoft/zafira#1293]
Environment: Win'10, Chrome 71.0.3578.98, 64 bit
Zafira environment: stage
Steps:
1. Click '+' button to create a new widget
2. Enter necessary fields Title and type
3. Click Create button
Actual result: Error "unable to create widget"
Expected: ??? tbd

**Comment by vdelendik** [comment]
out-of-dated as widget creation procedure completely redesigned
