### ISSUE TITLE
Vertical scroll bar is absent and user can't scroll the page

### ISSUE THREAD

**Issue by Annett14** [qaprosoft/zafira#1295]
Environment: Win'10, Chrome 71.0.3578.98, 64 bit
Zafira environment: stage
Repro rate: 2/5
Steps:
1. Open any dashboard
2. Try to scroll the page down
**Actual result**: there is no vertical scroll bar and user can not scroll the page
**Expected result**: user can scroll the page
[Screenshot](https://www.dropbox.com/s/cjdne8ena0zr7sp/vertical%20scroll.png?dl=0)

**Comment by vdelendik** [comment]
already fixed
