### ISSUE TITLE
default ZAFIRA_ELASTICSEARCH_URL has reference to localhost incorrectly

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1299]
https://github.com/qaprosoft/zafira/blob/67657606d24117720d3dd41b6a5a002de2960256/integrations.env#L16

We can't use localhost here and seems like 9200 is one more requirement to open port for Zafira server.
On AWS instances with public/private IP and limited number of shared ports elasticsearch can't be configured at all.

**Comment by hursevich** [comment]
This is default config for local deployment, like we do specify localhost for default backend. For cloud deployment you have to provide correct public IP or host name. By the way you are capable to expose any allowed port in required by AWS range.
