### ISSUE TITLE
Zafira header gets corrupted after assigning new issue to the failed test

### ISSUE THREAD

**Issue by mohamadli** [qaprosoft/zafira#1321]
Steps to repro:
1) For any failed test in Zafira
2) Click on issue button to trigger Test  Detail Modal Dialog
3) Move to Issues Tab
4) Link an issue
5) Press Assign Button
Actual result:
![image](https://user-images.githubusercontent.com/47204765/52426472-e5d50900-2ab2-11e9-89f8-001c2818a17a.png)

**Comment by Ageenkooo** [comment]
Can't reproduce on stage, could you please give some details

**Comment by vdelendik** [comment]
reopened
