### ISSUE TITLE
Zafira Portal RabitMQ and zafira-ws not working

### ISSUE THREAD

**Issue by punyadotnet1** [qaprosoft/zafira#1334]
Zafira is not working .The Zafira portal is up but not able to run it by using testng .The below service is down.

Need all your help for proper installation.

http://localhost:8080/zafira-ws/

**Comment by vdelendik** [comment]
@punyadotnet1, please tell me what's OS do you use and attach logs from postgres container.

**Comment by vdelendik** [comment]
@punyadotnet1, you should use such URL to access zafira ui:
http://localhost:8080/zafira
