### ISSUE TITLE
Ignore queued tests in Zafira if the test_run_rules filter was used

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1359]
If **test_run_rules** parameter in config.properties is not NULL and not empty - tests will be executed based on filter logic: 
For example: 
test_run_rules=PRIORITY=>P1&amp;&amp;P2;;OWNER=>msarychau;;TAGS=>tag1=temp&amp;&amp;feature=reg
rules logic: test_run_rules={RULE_NAME_ENUM}=>{RULE_VALUE1}&&{RULE_VALUE2}...

But in such cases, a lot of tests in Zafira reports are marked as Queued.  
They should be ignored and not visible in reports and statistic.

**Comment by maksimsarychau** [comment]
@vdelendik Please add your comments if any.

**Comment by tsvrko** [comment]
Will be resolved via enhancement https://github.com/qaprosoft/qps-pipeline/issues/334
