### ISSUE TITLE
Add possibility to re-map test owner in Zafira.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1360]
In some situations, when people who have a bunch of existing tests executing on a daily base, leave the project. Of course, it is possible to change the owner in the sources. But it will take time. 
It will be good to remap somehow all or some of these tests in Zafira to show and calculate them correctly with a new owner. 
Also, new test tag can be added (based on existing test tag feature) with info of the previous owner.

**Comment by hursevich** [comment]
Not possible to implement by backend design.
