### ISSUE TITLE
Test details/test info page issues

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/zafira#1367]
Gallery controls are cut in mobile layout:
![IMG_0652](https://user-images.githubusercontent.com/1182755/54304048-6bc60180-45d5-11e9-9b07-1cc225ae6710.PNG)
Also take a look on strange errors in console:
<img width="1680" alt="Screen Shot 2019-03-13 at 8 40 08 PM" src="https://user-images.githubusercontent.com/1182755/54304077-78e2f080-45d5-11e9-90aa-fc688ab67ef8.png">
Would be nice to fix context menu that opens test logs and issues:
1. Menu items should start from upper letter Issues / Details (renamed from details / overview)
2. Menu items in mobile layouot should be clickable on text as well - now only icon
![IMG_0653](https://user-images.githubusercontent.com/1182755/54304360-0c1c2600-45d6-11e9-9f98-da0c81bed81d.PNG)
---------------
When test in progress and I navigate back from test logs to the test run results looks like that we are not unsubscribed from elasticsearch repeating calls, I see loading line every 5 seconds - we have to unsubscribe from it.

**Comment by danymill** [comment]
fixed
