### ISSUE TITLE
If zafira's test run was restarted to rerun failures - run disappears

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#1379]
Say, i need to rerun failed tests.
to do that i search for test run i need and do rebuild failures on that run.
wait for spinner is triggered and reload the page.

Test run is removed from zafira.

**Comment by vdelendik** [comment]
not a bug.
it disappeared from test runs until it is in queue and compilation is running. We are going to refactor queued status display for better handling such use-case
