### ISSUE TITLE
Test is duplicated within one test run

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#1392]
server v.3.3.48 | client v.3.3.51

I've set retry count = 3
after that i saw that one test is marked twice within one test report

failed test:
TEST SECTION - test name

passed test:
TEST SECTION - test name (InvCount=0002)

also this situation ended up with increasing actual test amount by 1 (expected count is 80, but there're 81 test displayed on Zafira)

**Comment by vdelendik** [comment]
@Litsvin is it still actual?
