### ISSUE TITLE
Provide a possibility to skip test from java test code

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#1423]
As a QA-automation, I'd like to have a possibility to throw some kind of skipException and have relevant test skipped in Zafira's test run.

Some time ago we could use, for instance, following exception to make test yellow on Zafira, but now it doesn't work:
org.testng.SkipException.SkipException

**Comment by vdelendik** [comment]
@Litsvin 
if you make a SkipException TestNG call then it just generates skipped test in Zafira.
to skip and don't register something you should use
skipExecution(string message);
which is available on any test class level.
https://github.com/qaprosoft/carina/blob/bdd151c788cf51fa4d33df090aa726517e902cdb/carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java#L102
