### ISSUE TITLE
'Aborted' test runs counted as 'Queued' on Zafira dashboards

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1451]
Jenkins jobs, which were aborted due to different reasons, e.g. compilation error, these test run in Zafira is marked as Aborted, but on the Project and Personal boards all tests counted as Queued
Run:
![image](https://user-images.githubusercontent.com/4455896/55177047-a35ead00-5182-11e9-9454-532f3dd258a0.png)
Board:
![image](https://user-images.githubusercontent.com/4455896/55177085-b4a7b980-5182-11e9-8bc1-d6ee361d55d9.png)

**Comment by tsvrko** [comment]
done db59240bba2181ea31a3cd1051104894f1a7c8af
