### ISSUE TITLE
create *.svg icon pack for all supported in Zafira platforms

### ISSUE THREAD

**Issue by tsvrko** [qaprosoft/zafira#1471]
At the moment we have 14 platform icons:
**9** of them are already in **.svg* format (safari, chrome, firefox, edge, xbox, ps, ie, android, ios);
**5** are still taken from single **.png* template (**api, appletv, androidtv, tizen, unknown (N/D)**)
![image](https://user-images.githubusercontent.com/23284071/55475377-7ac03280-561c-11e9-96eb-9f06d1af6ae1.png)
**appletv** and **androidtv** both don't use their original logos because it didn't seem possible to squeeze those logos in 20x20 pixels space. So, any other more graceful solution is welcome here (same for **api** and **unknown**). At least current version of **.png* icons should be converted into vector, and the rest of **.svg* ones reviewed for possible improvements. 
As a result it would be nice to have a pack of icons in a common style. 
Current versions of images are attached below.
[platform_icons.zip](https://github.com/qaprosoft/zafira/files/3038515/platform_icons.zip)

**Comment by vabramova** [comment]
[_icons_platform.zip](https://github.com/qaprosoft/zafira/files/3103204/_icons_platform.zip)
