### ISSUE TITLE
Not able to login into the application

### ISSUE THREAD

**Issue by ketulmodi** [qaprosoft/zafira#1496]
I'm not able to login in to the zafira home page
![image](https://user-images.githubusercontent.com/49430404/55780003-8ac88e00-5ac4-11e9-9574-1c1aa08f1cd1.png)

**Comment by hursevich** [comment]
Hello, @ketulmodi 
Sorry to hear that, please pull the latest changes from master branch and start the application, default zafira url is http://localhost:80/app.

**Comment by ketulmodi** [comment]
Should i update the port on docker-compose.yml?
