### ISSUE TITLE
Startup failed: Timed out waiting for a signal from the JVM.

### ISSUE THREAD

**Issue by ketulmodi** [qaprosoft/zafira#1503]
I'm Using Windows 10 pro docker and have the following issue.
![image](https://user-images.githubusercontent.com/49430404/56012469-39114500-5d0a-11e9-861b-61dd10a68a4e.png)

**Comment by hursevich** [comment]
Try to allocate more resources to your docker, at least 2CPU and 4GB Ram.

**Comment by vdelendik** [comment]
@ketulmodi, any update on this issue? is it still actual?
Did you try already released qps-infra pack where zafira is already integrated into the bundle?
https://github.com/qaprosoft/qps-infra/releases/tag/4.0

**Comment by vdelendik** [comment]
@ketulmodi closing due to the no response
