### ISSUE TITLE
regression: unable to assign known issue even if jira integration is disabled

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1515]
1. expand test run, open menu for failed test and choose 'Assign issue'
2. type number and summary
-> error message is displayed that unable to connect to jira.
- assign button is disabled
![image](https://user-images.githubusercontent.com/4551455/56430209-4dd37700-62ce-11e9-9629-5953bfaeb4fb.png)

**Comment by vdelendik** [comment]
when jira integration is disabled end-user should be able to assign tickets on their own. In this case we can support 3rd party bug tracking like github etc with no extra development

**Comment by hursevich** [comment]
Resolved
