### ISSUE TITLE
usability issue for mass abort operation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1516]
image I selected all in progress runs to make mass abort operation.
As result 20 items are aborted but complains are
1) all of them are still selected/checked including global chechbox
-> aborted items should reset selected checkbox
Anyway I have to reset filter and apply it again 
OR
2) as variant I could switch to the next page but it is located at the bottom of the page
-> how about making page jumper at the right top corner where we have filter blocks?

**Comment by danymill** [comment]
@hursevich Could you provide appropriate texts for bulk operations (rerun, delete and abort) for both cases: success and failed; We will display one common message for each case instead of separate message for each API call. Thank you.
