### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by tbdyzm** [qaprosoft/zafira#1529]
I followed the guide and installed zafira, when I use qpsdemo/qpsdemo, I meet Invalid credentials.(Ubuntu18.04), Can you give me the detailed solution steps.Thanks lot.

**Comment by hursevich** [comment]
Sorry to hear that, I've just pushed all the latest changes to zafira:latest and zafira-ui:latest, what I recommend to do:
- remove zafira:latest image from your host
- remove zafira-ui:latet image from your host
- rm -rf pgdata/ esdata/ from the root of the project (if they appeared during the first run)
- run docker-compose script
I've checked everything on my local - works good, make sure you are using zafira-client at least 3.4.55.
