### ISSUE TITLE
zafira-ui nginx container failing to start correctly with log entries - sed: /usr/share/nginx/html/app/config.json: No such file or directory

### ISSUE THREAD

**Issue by sspieker-cc** [qaprosoft/zafira#1530]
While attempting to debug Zafira docker startup issues, I have externalized all of the dependent containers and left only the three zafira container in the docker-compose file.

When starting the containers, there are two errors appearing in the zafira-ui docker logs:
 docker logs c4c26bd3c757
sed: /usr/share/nginx/html/app/config.json: No such file or directory
sed: /usr/share/nginx/html/app/config.json: No such file or directory

Entrypoint.sh contains the SED commands that are failing:
more entrypoint.sh
#!/bin/sh

# Config updates
sed -i -e 's#http://localhost:8080/zafira-ws#'"$ZAFIRA_WS_URL"'#g' '/usr/share/nginx/html/app/config.json'
sed -i -e 's#1.0-SNAPSHOT#'"$ZAFIRA_UI_VERSION"'#g' '/usr/share/nginx/html/app/config.json'

The path specified for the config.json file does not exist and the file is not found anywhere within the container.

I cannot find a config.json file within the zafira project so I am assuming that it is supposed to be stored within the container.  There is a lot of black magic going on in terms of setting up the containers and when some error occurs there is not very good visibility into why or where the issue is stemming from.  Perhaps I might be able to join this project and contribute to the documentation effort for some of the issues I have faced with getting the Zafira tools to even run.

**Comment by hursevich** [comment]
Nginx config should be there for sure, plz check Dockerfile:
- https://github.com/qaprosoft/zafira-ui/blob/develop/Dockerfile#L24
- https://github.com/qaprosoft/zafira-ui/blob/develop/Dockerfile#L35
<img width="1018" alt="Screen Shot 2019-05-01 at 8 20 41 AM" src="https://user-images.githubusercontent.com/1182755/57006506-0a400d80-6bea-11e9-8fdb-022fcd3b89e1.png">

**Comment by sspieker-cc** [comment]
I have found the config.json file within the zafira-ui cloned project.  I have added it to the zafira's config directory and modified the docker-compose.yml file in order to place it in the correct location when the container starts.

**Comment by sspieker-cc** [comment]
I had found the file presence in the zafira-ui project, however, the docker image that was being deployed did not contain the file itself.  I had updated the docker compose to include the file from the config directory of the zafira project relative to the docker-compose file.  This seems to be a workaround that is working for me at this time.
