### ISSUE TITLE
Incorrect display of special characters in Send by email

### ISSUE THREAD

**Issue by mohamadli** [qaprosoft/zafira#1536]
Cloud Zafira “Send by email” functionality replaces characters in the body
Examples:
Tab -> Â (to format a table)
‘ -> â€™ (can’t)

Besides that, intervals between lines in “Send by email” body during editing and in the delivered email differ.

As a user I expect that the delivered email matches the style and character set of the composed email in Zafira.

Reproducible in Cloud Zafira.

I see in Zafira:
![image](https://user-images.githubusercontent.com/47204765/57092928-402de080-6d15-11e9-9cec-2132a83b1b79.png)

I get in mail:
![image](https://user-images.githubusercontent.com/47204765/57092978-5b98eb80-6d15-11e9-9120-58465a532a4a.png)

**Comment by hursevich** [comment]
Working on it
