### ISSUE TITLE
Zafira does not show logs in Firefox v.66.0.3

### ISSUE THREAD

**Issue by dmitry-minchuk** [qaprosoft/zafira#1539]
![Screen Shot 2019-05-07 at 12 01 56](https://user-images.githubusercontent.com/19321365/57290378-f6067f80-70c5-11e9-8777-a997305e377c.png)
![Screen Shot 2019-05-07 at 12 04 11](https://user-images.githubusercontent.com/19321365/57290395-fe5eba80-70c5-11e9-9e29-7f899d3eb750.png)

**Comment by hursevich** [comment]
Working on it
