### ISSUE TITLE
queue registration should be updated based on latest fixes

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1556]
in 4.0.52 we delivered improved abort logic so there is no way to keep tests in "queued" state anymore. As result our logic with queue registration + testcase removal is broken again:
1) we successfully executed and registered 100 tests per suite
2) during refactoring 30 of them we removed
3) right after removal next run will contain 70 pass and 30 queued which are translated to 'aborted" on finish
4) for next run queue registration again register 100 as expected number and we can't correct it until disable queue registration

please update logic and don't copy "queued" and "aborted" tests during queue registration

**Comment by tsvrko** [comment]
Works as expected, current situation is caused by 2 events happened at the same time (tests removal and abort by timeout), which is usually unlikely and will be resolved when run is finished without abort.
