### ISSUE TITLE
regression: tests work items declaration allow duplicates

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1557]
In tags registration in zafira-client was updated a little bit. Not sure if it a real root cause but starting from 4.0.52 we register test tags twice:
1) on before test
2) on after test

Also in our production databases I see that duplicates are being created right after migration (May, 15)
Duplication means that in the test_work_items there are several lines with where test_id and work_item_id are the same.
 id           ; test_id  ; work_item_id; created_at
45058131;107119680;34961;"2019-05-15 02:13:20.354465"
45078037;107119680;34961;"2019-05-15 10:30:53.984916"

so based on created_at date we have problem in detecting existing tags and register one more with the same values

**Comment by hursevich** [comment]
How does test tags correlate with work items declaration? I was trying to identify tags duplicates running:
select test_id, count(*) from stage.test_tags group by test_id, tag_id having count(*) > 1;
but nothing was found.

**Comment by vdelendik** [comment]
fixed in 4.0.53+
