### ISSUE TITLE
need effective way to avoid existing widgets param modifications

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1558]
When I assign existing widget to my board I have ability to change default params. As result it automatically change params in original widget which is not good.
It make sense to follow such strategy as a hotfix:
1) if existing widget is assigned to board without params modification -> asiign the same one
2) if any of param is updated including name or desc then create new one based on new args

**Comment by vdelendik** [comment]
as extra negative use-case: if user assign existing widget and rename it then board is corrupted and new wizard can't be placed at all. Only removal and extra assignment fix the issue

**Comment by hursevich** [comment]
Not user is informed about possible updates on other dashboards.
