### ISSUE TITLE
performance: we have very slow parameter load on widget creator

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1559]
We have 10-11 queries which executed for 100ms, one of them return 1000+ lines. As result when we click SHOW MORE we should wait upto 10-15 seconds.
It seems like generating dropdown with such values are very slow or queries are executed in non-optimized mode.

**Comment by hursevich** [comment]
Is that query optimization only?

**Comment by vdelendik** [comment]
fixed by avoiding huge values list select, i.e. keep them as regular string value to type.
fix already in 4.0.60+
