### ISSUE TITLE
AI: during queue registration predict each test result state

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1562]
We should provide embedded AI model with auto-training abilities to predict test state right after start.
As input fields we can define:
-current datetime (to detect possible sprints phases etc)
-last X states
-assigned tickets/bugs (known issues)
-changed jira tickets by devs for this project 
-list of actual known issues with actual states from jira (github)
etc

Later I'd like to see estimated pass rate for huge regression milestone in seconds but not in a minutes/hours when all regression is finished.
Also it should be auto-trainable as right after execution we could return actual results and compare with predicted one so initial probability could start from 50%/50% at all.

And finally it allow to generate list of testcases with the most risky areas where we see the biggest risk of changing to fail

**Comment by hursevich** [comment]
Useless.
