### ISSUE TITLE
Unable to scroll test runs while notifications are active

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#1569]
Once the process of sending email(s) / deleting test run(s) is started, user isn't able to scroll test runs page until all the notifications are completed. However, other interactions with the test runs, such as opening of specific test run, using search filters are available
<img width="335" alt="emailNotification" src="https://user-images.githubusercontent.com/21850997/58078839-59a9a600-7bb8-11e9-865c-50953ca0f245.png">

**Comment by danymill** [comment]
fixed
