### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by zhongyong** [qaprosoft/zafira#1572]
Invalid credentials
postgres:
qpsdemo  Yi4kaKFWK90GHE31L4z5WuGzsG3QpRGo

**Comment by vdelendik** [comment]
Hey @zhongyong.
1. Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
https://github.com/qaprosoft/zafira/tree/4.0.54
2. Did you try qpsdemo/qpsdemo as creds?
3. Did you take a look into fully CICD solution where zafira is provided as embedded reporting tool: https://github.com/qaprosoft/qps-infra/releases/tag/4.0

**Comment by zhongyong** [comment]
谢谢，明天试试，我今天用的是开发分支。------------------ 原始邮件 ------------------
发件人: "vdelendik"<notifications@github.com>
发送时间: 2019年5月22日(星期三) 晚上9:04
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "zhongyong"<18455668@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Invalid credentials (#1572)



Hey @zhongyong.
  
Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
 https://github.com/qaprosoft/zafira/tree/4.0.54
 
Did you try qpsdemo/qpsdemo as creds?
 
Did you take a look into fully CICD solution where zafira is provided as embedded reporting tool: https://github.com/qaprosoft/qps-infra/releases/tag/4.0
  
&mdash;

**Comment by zhongyong** [comment]
Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
https://github.com/qaprosoft/zafira/tree/4.0.54

Did you try qpsdemo/qpsdemo as creds?
try 1 and 2  failed。

Method 3 is too complicated to try, especially the id permission




------------------ 原始邮件 ------------------
发件人: "vdelendik"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 晚上9:04
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "呐喊"<18455668@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Invalid credentials (#1572)




Hey @zhongyong.
  
Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
 https://github.com/qaprosoft/zafira/tree/4.0.54
 
Did you try qpsdemo/qpsdemo as creds?
 
Did you take a look into fully CICD solution where zafira is provided as embedded reporting tool: https://github.com/qaprosoft/qps-infra/releases/tag/4.0

**Comment by zhongyong** [comment]
------------------ 原始邮件 ------------------
发件人: "vdelendik"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 晚上9:04
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "呐喊"<18455668@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Invalid credentials (#1572)




Hey @zhongyong.
  
Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
 https://github.com/qaprosoft/zafira/tree/4.0.54
 
Did you try qpsdemo/qpsdemo as creds?
 
Did you take a look into fully CICD solution where zafira is provided as embedded reporting tool: https://github.com/qaprosoft/qps-infra/releases/tag/4.0

**Comment by zhongyong** [comment]
------------------ 原始邮件 ------------------
发件人: "vdelendik"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 晚上9:04
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "呐喊"<18455668@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Invalid credentials (#1572)

80--》8080    ip is localhost

Hey @zhongyong.
  
Did you clone zafira from 4.0.54 tag: https://github.com/qaprosoft/zafira/releases/tag/4.0.54?
 https://github.com/qaprosoft/zafira/tree/4.0.54
 
Did you try qpsdemo/qpsdemo as creds?
 
Did you take a look into fully CICD solution where zafira is provided as embedded reporting tool: https://github.com/qaprosoft/qps-infra/releases/tag/4.0

**Comment by zhongyong** [comment]
environment:
      - ZAFIRA_URL=http://172.16.0.20:8080
      - ZAFIRA_USER=qpsdemo
      - ZAFIRA_PASS=qpsdemo
      - ZAFIRA_GROUP="Super admins"
    depends_on:
      - "db"
      - "rabbitmq"
      - "redis"
    restart: always
  zafira-ui:
    image: qaprosoft/zafira-ui:latest
    ports:
      - 80:80
    environment:
      - ZAFIRA_WS_URL=http://172.16.0.20:8080/zafira-ws
ok

**Comment by vdelendik** [comment]
@zhongyong please ping me directly so we can organize a session with you to assist with problem detection.
