### ISSUE TITLE
Renamed suites have names which they have before renaming in dashboards and runs.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1584]
Steps. 
1. Find suite\job which was already executed and present in any daily based dashboard with suite names list
2. Rename it in suite xml file and commit. 
3. Execute onPush job if it was not started automatically.
4. Run this suite\job 
5. Check that suite name was not renamed in the dashboard. 

Expected result - suites should be renamed at least after rerun and refreshing daily view.

**Comment by vdelendik** [comment]
it is affected by queue registration logic only. But this use-case should be supported as well i.e.:
1) during queue registration we make a copy based on previous run
2) as only actual suite starts we have to sync suite name according to the latest changes if any

**Comment by vdelendik** [comment]
fixes are in zafira-client 4.0.57+
zafira 4.0.60+
