### ISSUE TITLE
zafira+jenkins integration doesn't work from time to time

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1586]
starting from 4.0 I see to often that "build now" and other jenkins integration functionality is not accessible. After looking into the integration view jenkins is marked as red.
Just saving the same values make integration green and return valid operations to the test runs

**Comment by hursevich** [comment]
Could you plz verify that you are using Jenkins token but not Jenkins password?

**Comment by Boniara** [comment]
cannot reproduce
