### ISSUE TITLE
Sorting tests in test run by status is reset after visiting page with attachments

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#1588]
to reproduce:

1) open test run
2) set filter to display only failed tests
3) clicl 'eye' icon to see attachments for one of failed tests
4) click back button to return to test run

Actual: filter is reset - all tests are displayed
Expected: only fail tests displayed

**Comment by hursevich** [comment]
Working on it

**Comment by hursevich** [comment]
Fixed
