### ISSUE TITLE
404 error in console 

### ISSUE THREAD

**Issue by akazachok** [qaprosoft/zafira#1596]
**Steps:**
1) Open the "Test Run" tab and console ( Dev tools => console)
2) Set the following parameters in the filter: 
_Search items = MMF
Status = FAILED
Environment = NONE
Platform = NONE_
3) Open any test run and select "View".

Or click on links and select "View" : 
https://stage.qaprosoft.farm/app/tests/runs/1514 https://stage.qaprosoft.farm/app/tests/runs/1511  

![404 error ](https://user-images.githubusercontent.com/51660874/59229975-ac3d1780-8be4-11e9-8dea-e2775d001bfe.png)

**Comment by hursevich** [comment]
This is ok for stage env, we may clear some logs that is why you are getting 404 in console.
