### ISSUE TITLE
500 error in console  

### ISSUE THREAD

**Issue by akazachok** [qaprosoft/zafira#1599]
**Steps:**
_**Note:**_ Not always reproducible. 
1)Open the "Test Run" tab and console ( Dev tools => console)
2)Set the following parameters in the filter:
_Search items = MMF
Status = FAILED
Environment = NONE
Platform = android_
3) Open any test run

**Follow the link where 100% repro**
https://stage.qaprosoft.farm/app/tests/runs/269
https://stage.qaprosoft.farm/app/tests/runs/367
https://stage.qaprosoft.farm/app/tests/runs/132
https://stage.qaprosoft.farm/app/tests/runs/97
https://stage.qaprosoft.farm/app/tests/runs/1874

![500_error_zafira](https://user-images.githubusercontent.com/51660874/59279749-2add9780-8c6d-11e9-80a4-a18decffe46a.png)

**Comment by Boniara** [comment]
async supported parameter was added to servlet and to all servlet filters
