### ISSUE TITLE
No tooltips for the menu items in the left sidebar

### ISSUE THREAD

**Issue by tsevostian** [qaprosoft/zafira#1603]
As a user I'd like to see tooltips when hovering over the buttons in the left sidebar.

![giphy](https://user-images.githubusercontent.com/51750674/59357291-3b584580-8d33-11e9-8550-a20e9c44dddd.gif)

**Comment by mohamadli** [comment]
Was thinking about something similar to what Artifactory has for their left sidebar

**Comment by hursevich** [comment]
Let's show them after small timeout 2-3 sec.

**Comment by hursevich** [comment]
Will not be implemented by design.
