### ISSUE TITLE
General tab does not open and does not show dashboards after double-clicking on Zafira button on the left sidebar

### ISSUE THREAD

**Issue by nikitazihadlo** [qaprosoft/zafira#1604]
Steps:

1. Open Zafira
2. Log in
3. double-click on Zafira button on the left sidebar

Actual result:

General tab does not open and does not show dashboards after double-clicking on Zafira button on the left sidebar
![Screenshot_3](https://user-images.githubusercontent.com/45146672/59358083-9f2f3e00-8d34-11e9-9cf3-76309d508f34.jpg)

Expected result:

The “General” tab opens and shows dashboards after double-clicking on Zafira button on the left sidebar

**Comment by hursevich** [comment]
Duplicate for https://github.com/qaprosoft/zafira/issues/1604
