### ISSUE TITLE
Search field and other filters are disabled while any predefined  filter is set.

### ISSUE THREAD

**Issue by imatskevich** [qaprosoft/zafira#1607]
1 Navigate to test runs tab https://stage.qaprosoft.farm/app/tests/runs
2 Filter by Mobile runs

Result: Search field is deactivated.

![ice_video_20190612171443](https://user-images.githubusercontent.com/33233052/59360053-28943f80-8d38-11e9-9591-a4d1c52828c9.gif)

**Comment by hursevich** [comment]
Not a bug, filters and search functionality are not allowed to combine.
