### ISSUE TITLE
User has no possibility to set 2 filters at once

### ISSUE THREAD

**Issue by imatskevich** [qaprosoft/zafira#1608]
1 Navigate to test runs tab https://stage.qaprosoft.farm/app/tests/runs
2 Filter by Mobile runs
3 Add another filter by Passed

Result: filters exclude each other. Only one filter can be applied at a time.

![ice_video_20190612171345](https://user-images.githubusercontent.com/33233052/59363133-59c33e80-8d3d-11e9-817a-3ee21f1d29d1.gif)

**Comment by hursevich** [comment]
Not a bug, works like that by initial design.
