### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by ipapelishvili** [qaprosoft/zafira#1609]
Win 10, Chrome 74.0.3729.169 (Official Build) (64-bit)
Steps:

- Click button Test Runs
- Click Burger button on bottom-right corner
- Click button "send as email"
- Enter your email
- Click button "Send"
Actual result: Nothing happens 
Expected result: Email sent

**Comment by hursevich** [comment]
Not repro

**Comment by ipapelishvili** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/51718078/59462406-58247400-8e2c-11e9-8072-d5b46a8889ef.jpg)
Today this button is absent

**Comment by Boniara** [comment]
@ipapelishvili , the bug is not repro, could you please provide us url to the app, video with steps to reproduce

**Comment by hursevich** [comment]
Not repro
