### ISSUE TITLE
Multiple android and ios platforms are shown while adding new widget

### ISSUE THREAD

**Issue by imatskevich** [qaprosoft/zafira#1610]
1 Open any Dashboard.
2 Add New widget.
3 Select any template and hit Next.
4 Hit Show more and toggle on PLATFORM.
5 Open PLATFORM dropdown.

Actual result: multiple android and iOS platforms are present (in upper and lower case).

![Screen Shot 2019-06-13 at 12 05 19 PM](https://user-images.githubusercontent.com/33233052/59420363-7448f680-8dd5-11e9-8ad5-ec4fc53a00d2.png)
<img width="789" alt="1" src="https://user-images.githubusercontent.com/33233052/59420376-7b700480-8dd5-11e9-913c-d8771dc09530.png">

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/zafira/commit/981c759c6cca0acc624ca2c61c6a715bf28a5bcf
004_pg-alter-30-06-2019.txt alter script applied on production (no duplication anymore)
