### ISSUE TITLE
500 error after setting extended parameters for a new widget (period Total)

### ISSUE THREAD

**Issue by imatskevich** [qaprosoft/zafira#1612]
1 Open any dashboard.
2 Add new widget.
3 Select any Template (for example Test Cases by Stability) and hit Next.
4 Select Period Total.
5 In Show more Switch on Project and Platform.

Actual: Unable to execute SQL message and 500 error in console.

![ice_video_20190612211925](https://user-images.githubusercontent.com/33233052/59422147-8ed09f00-8dd8-11e9-8672-35bdb7d0729f.gif)

**Comment by vdelendik** [comment]
@imatskevich, good catch!
Fixed: https://github.com/qaprosoft/zafira/commit/c657a7fac4193c95d01a346df630122948065992

Also applied on most importance instances
