### ISSUE TITLE
Zafira: "Create" button looks active and has a green color when you create a user and enter invalid values ​​in the registration fields

### ISSUE THREAD

**Issue by nikitazihadlo** [qaprosoft/zafira#1613]
![Screenshot_1](https://user-images.githubusercontent.com/45146672/59468031-ca4f8580-8e39-11e9-9bfa-69c5852102da.jpg)

**Expected result:** 
“Create” button looks inactive and has a gray color when you create a user and enter invalid values ​​in the registration fields

**Comment by hursevich** [comment]
Fixed
