### ISSUE TITLE
Should be “Recipients” instead of “Recepients” field

### ISSUE THREAD

**Issue by hshugaleeva** [qaprosoft/zafira#1615]
1. tap send by email for any widget on dashboard 
2. look at “Recepients” field

Result: Should be “Recipients” instead of “Recepients” field

<img width="235" alt="Screen Shot 2019-06-14 at 4 13 04 PM" src="https://user-images.githubusercontent.com/36439738/59511887-19d89480-8ec0-11e9-9032-2d2fa0ddf7d8.png">

**Comment by lmikhadyuk** [comment]
![Uploading Снимок экрана 2019-10-29 в 14.43.01.png…]()

**Comment by Ageenkooo** [comment]
just fixed by @Boniara
