### ISSUE TITLE
The last letter is partially cut in subject and recipients fields

### ISSUE THREAD

**Issue by hshugaleeva** [qaprosoft/zafira#1616]
1. tap send by email for 30 DAYS TOTAL widget (or other) 
2. enter a long email 

Result: the last letter is partially cut in subject and recipients fields

<img width="886" alt="Screen Shot 2019-06-14 at 4 03 46 PM" src="https://user-images.githubusercontent.com/36439738/59512086-9ff4db00-8ec0-11e9-995a-41e83973e0ca.png">

**Comment by Boniara** [comment]
@hshugaleeva it is not a bug. Letter subject input has a fixed width, recipients input has fixed width as well. Added possibility to build chip on blur for recipients input
