### ISSUE TITLE
Popup with "30 DAYS PASS RATE BY PLATFORM" graph details is cut

### ISSUE THREAD

**Issue by hshugaleeva** [qaprosoft/zafira#1618]
1. 30 DAYS PASS RATE BY PLATFORM graph 
2. Hover over firefox, ie, iexplore results 

Result: popup with details is cut

<img width="909" alt="Screen Shot 2019-06-14 at 3 49 28 PM" src="https://user-images.githubusercontent.com/36439738/59512526-97e96b00-8ec1-11e9-820e-66108aad5ca2.png">
<img width="846" alt="Screen Shot 2019-06-14 at 3 49 37 PM" src="https://user-images.githubusercontent.com/36439738/59512527-97e96b00-8ec1-11e9-8860-559d11558580.png">

**Comment by Boniara** [comment]
Done! Added 'confine' option to chart tooltip
