### ISSUE TITLE
Page blinks after I tap … button

### ISSUE THREAD

**Issue by hshugaleeva** [qaprosoft/zafira#1620]
1. Dashboard
2. Tap … button for 30 DAYS TEST DETAILS and 30 DAYS TESTS TREND

Result: Page blinks 

https://www.dropbox.com/s/3f2awn42zfyx9pc/blinks.mov?dl=0

**Comment by danymill** [comment]
@hshugaleeva I can't reproduce it on current UI. Could you re-check? If reproduces, please provide more details: device, OS. Thank you.

**Comment by hshugaleeva** [comment]
I still can reproduce on my macbook pro 13'' @danymill

**Comment by danymill** [comment]
@hshugaleeva What is your UI version?
![image](https://user-images.githubusercontent.com/6594800/61039574-b024ab00-a3d7-11e9-8eb9-af19782242d6.png)

**Comment by hshugaleeva** [comment]
<img width="353" alt="Screen Shot 2019-07-11 at 12 43 05 PM" src="https://user-images.githubusercontent.com/36439738/61040610-9dab7100-a3d9-11e9-999d-5e308de713e6.png">
@danymill
