### ISSUE TITLE
Zafira: "Create" button looks active and has a green color when you create a dashboard and do not enter a name in the title field

### ISSUE THREAD

**Issue by nikitazihadlo** [qaprosoft/zafira#1621]
![Screenshot_3](https://user-images.githubusercontent.com/45146672/59538707-5a0d3680-8f03-11e9-9d72-fcbd195464d8.jpg)
**Expected result:** 
“Create” button looks inactive and has a gray color when you create a dashboard and do not enter a name in the title field

**Comment by hursevich** [comment]
Fixed
