### ISSUE TITLE
Unable to use filter while search field is not empty and vice versa

### ISSUE THREAD

**Issue by ekazachenka** [qaprosoft/zafira#1641]
Would be nice if there was posibility to filter search results by using existing or creating new parameter set (Filter) on Test Runs screen and vice versa
If user types anything in search field -  Parameter Sets are disabled
If user enable Parameter Set(filter) - Search field is disabled
 found here: https://stage.qaprosoft.farm/app/tests/runs
![9MIaLba](https://user-images.githubusercontent.com/36449756/60458483-61447c00-9c47-11e9-81e7-80ccef75c35b.png)
![sqfbdIX](https://user-images.githubusercontent.com/36449756/60458487-673a5d00-9c47-11e9-9a96-760ae891c42f.png)

**Comment by hursevich** [comment]
This is by design.
