### ISSUE TITLE
From time to time known issues don't link to failed tests which logs stay the same

### ISSUE THREAD

**Issue by katedkm** [qaprosoft/zafira#1645]
There is an example when failed test is linked  with it's known issue (testPublicAndFriendWorkouts): https://ua.zebrunner.com/app/tests/runs/23663
This example is related to case when we don't see linked bug with test 'testPublicAndFriendWorkouts':
https://ua.zebrunner.com/app/tests/runs/23515

P.S. These 2 reports are daily regression runs without reruns.

**Comment by tsvrko** [comment]
Ticket can't be attached if Jira tool is disabled. 
Because of problems with Jira integration for past couple of days (on atlassian side), tickets weren't attached, but as soon as Jira tool works fine now this issue shouldn't be reproduced.
