### ISSUE TITLE
usability: after running repo scan it is recommended to open/expand those repo and show all jobs 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1661]
1. Activate Test Runs -> Test Launchers
2. Click "edit/setting" icon for any repo
3. initiate scan/rescan
4. wait until process is finished
5. click "Back To List"
-> I'd recommend to activate/expand this repo and show all jobs
For now we continue to see settings page for the repo

**Comment by hursevich** [comment]
Done.
