### ISSUE TITLE
Website is failed to load icons

### ISSUE THREAD

**Issue by tbdyzm** [qaprosoft/zafira#1663]
I'm sorry to trouble you that the zafira website is failed to load icons when I login. I just followed the tutorial, git clone the repo, then used ./start.sh to setup, then I opened the login page in chrome. And background is failed to load and after navigating to the dashboard, all icons were failed to load.I'm looking forward to your enthusiastic proposal, thks.
![1](https://user-images.githubusercontent.com/41499236/61095486-37305c80-a486-11e9-8fb4-a8064297f492.png)

**Comment by hursevich** [comment]
Hello, @tbdyzm 
Could you please provide a little bit more context, what OS do you use, what docker image version of zafira-ui? Are you using any specific firewall/antivirus rules?
You have to check availability of the following resources on your host:
- https://ajax.googleapis.com
- https://fonts.gstatic.com

**Comment by tbdyzm** [comment]
My os system is centOS(3.10.0-957.21.3.el7.x86_64), and browser is Chrome/Firefox, and I couldn't open the two pages you mentioned.
![1](https://user-images.githubusercontent.com/41499236/61111570-79749080-a4bc-11e9-86ea-9869a9b965e7.png)
![2](https://user-images.githubusercontent.com/41499236/61111575-7d081780-a4bc-11e9-819c-73a1f57162ce.png)
![3](https://user-images.githubusercontent.com/41499236/61111580-7f6a7180-a4bc-11e9-9c72-99e57e005f72.png)

**Comment by tbdyzm** [comment]
My os system is centOS(3.10.0-957.21.3.el7.x86_64), and browser is Chrome/Firefox, and I couldn't open the two pages you mentioned.


------------------ 原始邮件 ------------------
发件人: "Alex Khursevich"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 下午3:36
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "琉璃碎瓦"<1320007028@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Website is failed to load icons (#1663)




Hello, @tbdyzm
 Could you please provide a little bit more context, what OS do you use, what docker image version of zafira-ui? Are you using any specific firewall/antivirus rules?
 You have to check availability of the following resources on your host:
  
https://ajax.googleapis.com
 
https://fonts.gstatic.com

**Comment by hursevich** [comment]
Not sure about your current location but here is some information for China: https://meta.stackoverflow.com/questions/258288/use-of-ajax-googleapis-com-not-china-friendly

**Comment by danymill** [comment]
@tbdyzm Could you share the screen with browser's console?

**Comment by tbdyzm** [comment]
> @tbdyzm Could you share the screen with browser's console?

Here is the chrome console info: 
![1](https://user-images.githubusercontent.com/41499236/61122134-98325180-a4d3-11e9-869e-62380a458425.png)

**Comment by tbdyzm** [comment]
> Not sure about your current location but here is some information for China: https://meta.stackoverflow.com/questions/258288/use-of-ajax-googleapis-com-not-china-friendly

I used rm -rf to delete zafira, and then I used qps-infra to start zafira, icons were unloaded again, so I used rm -rf to delete qps-infar.Then I git clone zafira to restart, I got the info "Invalid credentials".Does the system can only setup zafira once?The second time when you setup, you'll get the info "Invalid credentials".

**Comment by danymill** [comment]
@tbdyzm Is your issue with icons solved? Can we close this? (For other troubles please open new issue, thx)

**Comment by tbdyzm** [comment]
> @tbdyzm Is your issue with icons solved? Can we close this? (For other troubles please open new issue, thx)

Sorry, the issue with icons was not resolved, I'm trying to fixed with it using some proposals.

**Comment by danymill** [comment]
@tbdyzm Oh, I see. Could you share this tab? :) 

![image](https://user-images.githubusercontent.com/6594800/61130376-323bcf00-a4bf-11e9-9fc4-0c022a014883.png)

**Comment by tbdyzm** [comment]
> @tbdyzm Oh, I see. Could you share this tab? :)
> 
> ![image](https://user-images.githubusercontent.com/6594800/61130376-323bcf00-a4bf-11e9-9fc4-0c022a014883.png)
I'm appreciate for your enthusiasm help! Here is the console info:
![1](https://user-images.githubusercontent.com/41499236/61131578-2a465400-a4ec-11e9-83db-ebcdcf13dbde.png)

**Comment by tbdyzm** [comment]
> @tbdyzm Oh, I see. Could you share this tab? :)
> 
> ![image](https://user-images.githubusercontent.com/6594800/61130376-323bcf00-a4bf-11e9-9fc4-0c022a014883.png)
I've fixed it with a chrome extension，Github is https://chrome.google.com/webstore/detail/replace-google-cdn/kpampjmfiopfpkkepbllemkibefkiice
![1](https://user-images.githubusercontent.com/41499236/61135196-c1fb7080-a4f3-11e9-9f34-9d3757b41cad.png)
Thks for your enthusiastic attention!

**Comment by hursevich** [comment]
ok, then I can close the ticket?

**Comment by tbdyzm** [comment]
Yeah, thk you very much!




------------------ 原始邮件 ------------------
发件人: "Alex Khursevich"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 晚上10:28
收件人: "qaprosoft/zafira"<zafira@noreply.github.com>;
抄送: "琉璃碎瓦"<1320007028@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qaprosoft/zafira] Website is failed to load icons (#1663)




ok, then I can close the ticket?
