### ISSUE TITLE
all general and personal widgets have JOB_NAME filter enabled and empty

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1665]
We still have problem with default JOB_NAME filter for new Zafira instance. It is enabled but empty for all widgets in general+personal widgets
![image](https://user-images.githubusercontent.com/4551455/61183560-73f98080-a64b-11e9-80d0-42d0b94f7c32.png)

It is not affect results calculation but misleading from widgets administering point of view.

**Comment by nsidorevich** [comment]
Duplicates #1788, closing.
