### ISSUE TITLE
unable to abort test run if CI is not configured

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1667]
test run which is launched locally and hasn't any information about CI, i.e. ci url equals "http://localhost:8080/job/unavailable/0" can't be aborted.

1) start test locally with zafira integration
2) abort it on IDE
-> we could think about abort call on shutdownhook for carina as well
3) test run in zafira is displayed as "in progress"
4) abort it via Zafira UI
-> Error message that unable to abort CI job is displayed and sttaus still in progress
Expected: error message but status shoyuld be changed to aborted with appropriate tests recalculation

**Comment by tsvrko** [comment]
done
