### ISSUE TITLE
New test runs are shown in runs even if filtering applied. 

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/zafira#1674]
In case if I applied some filter the new started jobs are still shown for me, even if they don't match to my filter parameters.

**Comment by danymill** [comment]
Available on `1.291-SNAPSHOT` UI

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.27.RC2 | server v.4.1.81.RC1 | client v.4.1.65.
