### ISSUE TITLE
What's the URL of jenkins with stage.qaprosoft.farm?

### ISSUE THREAD

**Issue by tbdyzm** [qaprosoft/zafira#1677]
This is not even a problem but i just want to know. I found that https://stage.qaprosoft.farm/app/signin can login by using the default username/password. Results are showed in dashboard, so can i have an access to login the jenkins to learn the project and how to associate jenkins with zafira? If you think that i can, can you supply with the jenkins URL?
![1](https://user-images.githubusercontent.com/41499236/61850909-0d485280-aee8-11e9-9671-a53be288b542.png)

**Comment by hursevich** [comment]
Unfortunately no, the idea of shared Zafira is to abstract from CI layer providing the possibility to run and track results directly from Zafira UI.

**Comment by hursevich** [comment]
Feel free to contact me directly hursevich@gmail.com or use our telegram support channel: https://t.me/qps_zafira
