### ISSUE TITLE
swagger-ui website is blank

### ISSUE THREAD

**Issue by tbdyzm** [qaprosoft/zafira#1683]
Official swagger-ui website shows the api doc correctly while mine is blank!
![1](https://user-images.githubusercontent.com/41499236/61965696-68bb3300-b003-11e9-8444-31d7331d3378.png)
![2](https://user-images.githubusercontent.com/41499236/61965702-6e187d80-b003-11e9-9e96-d5c71d2b3d2b.png)

**Comment by vdelendik** [comment]
@tbdyzm , try to enable debug mode in vaiables.env adding:
ZAFIRA_DEBUG_MODE=true

by default swagger is not available.
