### ISSUE TITLE
Reset testrun comments during rerun

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1685]
after compilation failure or infrastrcuture problem we put into the comments error.
Even after fixing it and restart we continue to see such error message with 100% pass rate.
Let's do in such way:
any rebuild/rerun should clean test runs comment field if no "reviewed" flag added.
Reviewed means human analyzed and added his comment so we can keep it during rebuild. All the rest could be nulled right after restart/rebuild

**Comment by tsvrko** [comment]
done
