### ISSUE TITLE
Unable to send dashboards\widgets from Zafira

### ISSUE THREAD

**Issue by rkatuzhanets** [qaprosoft/zafira#1692]
After latest update 'send by email' functionality isn't working properly in Zafira, recipients don't have any emails

**Comment by hursevich** [comment]
Have you checked spam?

**Comment by rkatuzhanets** [comment]
@hursevich checked once again, after a certain period of time (≈20-30 seconds) email with results is available
ui v.1.11 | server v.4.0.60 | client v.4.0.57

**Comment by hursevich** [comment]
So, the ticket may be closed?

**Comment by rkatuzhanets** [comment]
Sure, it could be closed
