### ISSUE TITLE
Unexpected error has occurred. Please try again later

### ISSUE THREAD

**Issue by vlinsw** [qaprosoft/zafira#1695]
After I deployed the environment, this error message was prompted when I tried to send data to the interface. Could you help me find the reason.

url:
http://localhost:8080/zafira-ws/api/auth/refresh
body:
refreshToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiJCbzZWRUs4UjAyRXozRklTU2xLVWxNWVgvM1JpVjJlQiIsInRlbmFudCI6InphZmlyYSIsImV4cCI6MTMwNDEzNjY3MDYxfQ.ZSg7ZnkacPx9VJct597eOtcK9-aInGetix9f4-aiKNLAHd45y_auxxi9EpudNrxy8Ts9xdhpfamZiAtbkwXSiw
(Token is generated by user qpsdemo)

responses:
{
    "error": {
        "message": "Unexpected error has occurred. Please try again later.",
        "code": 500
    }
}

**Comment by nikitasidorevich** [comment]
Hi @vlinsw , any chance you can set zafira debug mode to true and provide detailed log output?

**Comment by vlinsw** [comment]
any update on this issue? @vdelendik

**Comment by vlinsw** [comment]
How to turn on debug mode @nikitasidorevich

**Comment by vdelendik** [comment]
@vlinsw, we have to enable it in variables like this one
https://github.com/qaprosoft/zafira/blob/3dbdeac928be1ff6dd32d0d0a05e5415e63e5da3/zafira-properties.env#L2
stop containers, remove them and start again

Also just collect all zafira container logs and attach please...
