### ISSUE TITLE
Zafira

### ISSUE THREAD

**Issue by shamirahamed1909** [qaprosoft/zafira#1699]
Hi Team,

I am trying to integrate my testng framework with Zafira. However, after hosting my zafira server in a docker container in linux machine, I am unable to pass on the results of the test execution to the zafira dashboard. The errors populating are different for every trial. Any assistance to help me with the sequential steps to integrate would be beneficial.

I can be reached at shamirahamed1909@gmail.com

**Comment by nikitasidorevich** [comment]
Could you please reach out to our support team [here](https://t.me/qps_zafira)? They'll be happy to guide you through the process.

**Comment by vdelendik** [comment]
@shamirahamed1909, were you able to fix the problems? Did you see above comment?
