### ISSUE TITLE
Zafira UI responsiveness - Windows 10

### ISSUE THREAD

**Issue by AbhiAuto** [qaprosoft/zafira#1715]
Below are the images of Zafira dashboard UI. We can see the page is not responsive when we increase or decrease the zoom levels of browser.

Screen Size 1920 : 1080 
Laptop OS : windows 10

![image](https://user-images.githubusercontent.com/26138640/62869296-331d8600-bd35-11e9-8a9c-6f74012d1601.png)

![image](https://user-images.githubusercontent.com/26138640/62869281-28fb8780-bd35-11e9-871a-06ab62e5b2ef.png)

**Comment by hursevich** [comment]
Still an issue?

**Comment by nsidorevich** [comment]
@lmikhadyuk let's try to reproduce this one. Will close it we won't succeed.

**Comment by lmikhadyuk** [comment]
Wasn't able to repro in ui v.1.275-SNAPSHOT | server v.1.445-SNAPSHOT | client v.1.0-SNAPSHOT.
