### ISSUE TITLE
Improve datetime support for linecharts

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#174]
Currently we provide as "x" type date which converted to datetime on zafira level.
It would be nice to be able to convert to day/month/quarter/year etc.

 "axes": {
    "x": {
      "key": "CREATED_AT",
      "type": "date",
      "ticks": "functions(value) {return 'wow!'}"
    }
  }

Example:
"type": "datetime" - existing approach
"type": "date" - only date without time
all the rest - TBD

**Comment by tsvrko** [comment]
Only 3 explicitly defined params could be set to n3-charts axes "type" property:  "linear", "log" or "date", further customization seems not possible.
