### ISSUE TITLE
Filtering by project or by platform (...etc) does not allow to avoid showing unwanted suites' runs from the other projects or with different settings some time later

### ISSUE THREAD

**Issue by dmitry-minchuk** [qaprosoft/zafira#1742]
For example if I set project E-COMM - 5 minutes later I will see the runs from the other projects and I have to select E-COMM again to clear unwanted data.

**Comment by vdelendik** [comment]
confirm that a lot of complains exists for the runtime results when filters are applied.
The best fix - allow to show runtime data which correlate to the current filter.

**Comment by hursevich** [comment]
Closed as duplicate.
