### ISSUE TITLE
improve ZafiraClient->registerTestRun methods

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1758]
1) move to deprecated state:
registerTestRunByHUMAN
registerTestRunBySCHEDULER
registerTestRunUPSTREAM_JOB

2) create new fresh
registerTestRun

new method should just get common parameters, maybe we can declare several the same methods with different dataset.

3) later when we test new implementation successfully we can remove deprecated methods and update DB (several fields can be removed completely)

**Comment by nsidorevich** [comment]
Already impletented here: https://github.com/qaprosoft/zafira-client/pull/7
