### ISSUE TITLE
support use-case when the same test class/method belongs to different projects

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1761]
improve primary key for test_cases to make project as part of it.
use-case: the same classes/tests are located in different suites. each of suite has their own project declaration.

Current implementation "migrate" results from one to another suite according to the latest run.
But we have to register the same test_case twice under different projects

**Comment by nsidorevich** [comment]
@Boniara please discuss with @vdelendik and share the outcome. If this one will be finalized we should proceed with implementation.

**Comment by Boniara** [comment]
will be fixed after #1870 merging
