### ISSUE TITLE
Default username and password not working

### ISSUE THREAD

**Issue by prakashpqa** [qaprosoft/zafira#1763]
I have installed the application as per instructions and application is up and running.

But the default un and pw (qpsdemo) are not working and I'm getting the error "Invalid credentials".

Updated: 22-Oct-2019

Even though I have given the IP address, some calls are being made to localhost. Please help.

![zafira](https://user-images.githubusercontent.com/30907200/67263240-12627100-f4da-11e9-9571-3b8e346b6960.gif)

**Comment by tbdyzm** [comment]
You can provide more information to locate your problem. For example, sometimes, zafira-ui starts while zafira doesn't start. Show the browser console please.

**Comment by xriser** [comment]
same issue.

**Comment by xriser** [comment]
also, it looks like ZAFIRA_API_HOST or ZAFIRA_WS_URL doesn't read properly.
I have setup VM on GC, cloned Zafira from git, then changed(uncomment image  qaprosoft/zafira:4.1.69 and comment build) 
Have setup external ip of VM to values in docker-compose.yaml:
env ZAFIRA_WS_URL, and zafira-properties.env (ZAFIRA_WEB_HOST, ZAFIRA_API_HOST) 
Traffic to 80,443,8080 also allowed. 

But when I try to login, I saw requests tried to send to localhost URLs.
http://localhost:8080/zafira-ws/api/settings/companyLogo
http://localhost:8080/zafira-ws/api/config/version
http://localhost:8080/zafira-ws/api/config/projects
http://localhost:8080/zafira-ws/api/auth/login

So, it doesn't work.

**Comment by tbdyzm** [comment]
> http://localhost:8080/zafira-ws/api/settings/companyLogo

Hey, you can use qps-infra to set up your own application, just use ./setup.sh ip to change your ip. Maybe what you changed in Zafira is not complete.

**Comment by xriser** [comment]
ok, I have cloned qps-infra, and run setup to take a look at the generated files.
So, I don't need all this staff in docker-compose, but I what found:
env_file:                                                                                                                                                                                              
      - variables.env  
mounted to backend and ui containers, but in zafira repo (https://github.com/qaprosoft/zafira/blob/develop/docker-compose.yml#L72)
only to the backend container.
It looks like, this is the issue.

**Comment by prakashpqa** [comment]
> also, it looks like ZAFIRA_API_HOST or ZAFIRA_WS_URL doesn't read properly.
> I have setup VM on GC, cloned Zafira from git, then changed(uncomment image qaprosoft/zafira:4.1.69 and comment build)
> Have setup external ip of VM to values in docker-compose.yaml:
> env ZAFIRA_WS_URL, and zafira-properties.env (ZAFIRA_WEB_HOST, ZAFIRA_API_HOST)
> Traffic to 80,443,8080 also allowed.
> 
> But when I try to login, I saw requests tried to send to localhost URLs.
> http://localhost:8080/zafira-ws/api/settings/companyLogo
> http://localhost:8080/zafira-ws/api/config/version
> http://localhost:8080/zafira-ws/api/config/projects
> http://localhost:8080/zafira-ws/api/auth/login
> 
> So, it doesn't work.

This is exactly what is happening...

**Comment by prakashpqa** [comment]
> You can provide more information to locate your problem. For example, sometimes, zafira-ui starts while zafira doesn't start. Show the browser console please.

I have added further information. Please help.
