### ISSUE TITLE
which method should I call to add screenshot to the log?

### ISSUE THREAD

**Issue by vlinsw** [qaprosoft/zafira#1768]
Like this, which method should I call to add screenshot to the log？
![image](https://user-images.githubusercontent.com/13415496/65398131-1cfcee00-dde8-11e9-9e5d-264e54879363.png)

**Comment by hursevich** [comment]
import com.qaprosoft.carina.core.foundation.webdriver.Screenshot;

Screenshot.capture(getDriver(), "Your comment!")
