### ISSUE TITLE
[Critical] 500 Status code appears when invited user (via LDAP) attempts to login first time 

### ISSUE THREAD

**Issue by username1995br** [qaprosoft/zafira#1776]
Steps to produce : 
1. Login to zafira ; 
2. Click [Users] button on left sidebar ; 
3. Click [Invitations] button ; 
4. Click [+Invite user] button in the right top corner of the screen ; 
5. Click [Choose Source] drop-down menu , select "LDAP" ; 
6. Click [Choose Group] drop-down menu , select any group ; 
7. Click [Enter an Email] field , input available email ; 
8. Click [Invite] button ; 
9. Logout from current user ; 
10. Go to according email box ; 
11. Click [Join now] button in the "Join the workspace" email ;
12. Input valid username into "Username" field ; 
13. Input valid password in "Password" field ; 
14. Click [Sign Up] button ; 

Expected result : 
User able to proceed and finish registration via email invite .

Actual result : 
"Failed to sign up" error message appears in the right bottom corner . 
User unable to proceed and finish registration via email invite . 

![500 zafira](https://user-images.githubusercontent.com/51786857/66148435-8fa46f80-e619-11e9-8ff0-1e4440e9d664.png)

**Comment by hursevich** [comment]
Fixed
