### ISSUE TITLE
A user who does not have certain privileges can browse through pages that require administrative privileges 

### ISSUE THREAD

**Issue by username1995br** [qaprosoft/zafira#1783]
By the way : those pages without content .
**Steps to produce :** 
1. Login as ordinary user (not admin) ;
2. Change current url's path to "/app/users/groups" or "/app/users/list" or "app/views/1" etc.  ;
3. Press [Enter] button .

**Expected result :** 
User redirected to the permitted resource - "Dashboards" screen .

**Actual result :** 
User redirected to the empty webpage .
![123](https://user-images.githubusercontent.com/51786857/66568616-7e57e780-eb72-11e9-880c-10f06f60586b.png)
![users](https://user-images.githubusercontent.com/51786857/66568618-7e57e780-eb72-11e9-9eb0-21d412c6bd09.png)

**Comment by danymill** [comment]
Available on `1.291-SNAPSHOT` UI

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.295-SNAPSHOT | server v.1.468-SNAPSHOT | client v.1.0-SNAPSHOT.
