### ISSUE TITLE
swagger-ui.html and swagger-resources are empty or errored

### ISSUE THREAD

**Issue by sspieker-cc** [qaprosoft/zafira#1786]
When attempting to access:
http://localhost:8080/zafira-ws/swagger-ui.html = 😱 Could not render e, see the console.
http://localhost:8080/zafira-ws/swagger-resource = Array is empty

Re-building the WS image with debug logging results in a great deal of information being output:

swagger-ui.html =
[swagger-ui.debug.log](https://github.com/qaprosoft/zafira/files/3713597/swagger-ui.debug.log)

swagger-resources =
[swagger-resource.debug.log](https://github.com/qaprosoft/zafira/files/3713605/swagger-resource.debug.log)

Google searching seems to lead to missing dependency jars.  So far, adding these recommended jars have failed to allow the build to succeed.

**Comment by nsidorevich** [comment]
@sspieker-cc can you confirm if this is something you can reproduce with latest Zafira version?

**Comment by nsidorevich** [comment]
Issue is no longer there, verified against 4.1.79

**Comment by bsakel** [comment]
I can see this issue in my local instance(Zafira version 4.1.83 pulled from docker hub on 10/01/2020) and the instance that is hosted at http://demo.qaprosoft.com/zafira-ws/swagger-ui.html has the same issue too.
