### ISSUE TITLE
Add an opportunity to delete project 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1814]
Select company icon in the left ribbon

Expected result: User should be able to delete added project

**Comment by nsidorevich** [comment]
This feature will be included in the upcoming Zafira release (4.1.80)

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.288-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT.
