### ISSUE TITLE
User should not be able to rerun only failures in passed test run

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1827]
1. Open test run tab 
2. Click 3 dots on passed test run
3. Select Rerun
4. Select Only failures
5. Click "Rerun" button
 
Actual result: User is able to rerun "only failures" in passed test run
<img width="1279" alt="Снимок экрана 2019-10-31 в 14 47 21" src="https://user-images.githubusercontent.com/56070333/67944379-67df0200-fbed-11e9-81a3-c450bb96080b.png">

Expected result: User is not able to rerun "only failures" in passed test run

**Comment by Boniara** [comment]
back end part was implemented

**Comment by danymill** [comment]
@nsidorevich FE part is `done` and merged
