### ISSUE TITLE
User should not be able to "Mark as failed" failed test

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1828]
1. Open test run tab 
2. Open test run
3. Click 3 dots on failed test
4. Select Mark as failed
5. Click ok"

Actual result: User is able to "Mark as failed" failed test
<img width="1274" alt="Снимок экрана 2019-10-31 в 14 56 57" src="https://user-images.githubusercontent.com/56070333/67944973-dc667080-fbee-11e9-9fde-340f7472bb67.png">

Expected result: User is not able to "Mark as failed" failed test

NOTE: The same with "Mark as passed" passed test

**Comment by nsidorevich** [comment]
Here we should add BE validation so API can raise proper error. However UI adjustments are also required.
@Boniara please let @danymill know once we'll be done with BE changes.

**Comment by Boniara** [comment]
@nsidorevich it`s just front end bug,

**Comment by danymill** [comment]
@nsidorevich FE part is `done` and merged

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.288-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT
