### ISSUE TITLE
Incorrect behavior of "Blocker" checkbox in assign issue window

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1833]
Steps:
1. Login to Zafira
2. Open test run tab 
3. Open test run
4. Click 3 dots on test
5. Select Assign issue
6. Enter valid Jira ID, Summary and select "Blocker" checkbox
7. Click "Assign" button
8. Close "Assign issue" window
9. Open "Assign issue" window again 
10. Select added issue

Actual result: "Blocker" checkbox is not selected
https://www.dropbox.com/s/pybe7qxutw3g9vh/123.mp4?dl=0
Expected result: "Blocker checkbox is selected

**OR**
1. Reproduce 9 steps
2. Enter added Jira ID
3. Delete Jira ID

Actual result: Checkbox is selected
https://www.dropbox.com/s/dd7t9fv28fslc0t/checkbox.mp4?dl=0
Expected result: Checkbox is not selected

**Comment by lmikhadyuk** [comment]
Second part of bug is reproducible in  ui v.1.24-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT.

**Comment by danymill** [comment]
Fixed on UI from v. `1.332-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.336-SNAPSHOT | server v.1.511-SNAPSHOT | client v.1.0-SNAPSHOT.
