### ISSUE TITLE
Can't assign issue

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [qaprosoft/zafira#1837]
**Precondition:**
User has run with failed tests

**Steps for reproduce:**
1) Open run
2) Click "More options" for failed tests 
3) Click "Assign issue" button
3) Type ticket number "Jira ID" field
4) Wait until the summary field is filled
5) Click "Assign" button

**Expected results:** bug is linked
**Actual results:** Error message. Error 500 in console
`{"error":{"message":"Unexpected error has occurred. Please try again later.","code":500}}`
<img width="321" alt="Screen Shot 2019-11-06 at 15 01 57" src="https://user-images.githubusercontent.com/42094408/68296861-9f92f180-00a6-11ea-85c1-c7af21ef1db4.png">

**Comment by tsvrko** [comment]
fixed in 1.438-SNAPSHOT, will be available in the upcoming maintenance release
