### ISSUE TITLE
Issues can be cloned

### ISSUE THREAD

**Issue by Ageenkooo** [qaprosoft/zafira#1858]
![Screen Shot 2019-11-13 at 12 16 46 PM](https://user-images.githubusercontent.com/22776909/68830472-d1b2dd80-06bc-11ea-9542-6940f610034c.png)

Case 1:
1 select assigned issue
2 select blocker checkbox
3 click update
4 reload
result: copied issue
expected result: issue status blocker

Case 2:
Update endpoint sometimes returns workitem with another id

**Comment by danymill** [comment]
TODO: refactor incorrect `deleteWorkItemFromList` and `deleteWorkItemFromTestWorkItems` (cause `[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: issue in $ctrl.issues track by issue.id` errors)

**Comment by hursevich** [comment]
The logic should work as follows:
1. List of historical tickets should be grouped by JIRA ID, we display only latest ticket by date for every logged item
2. Only 2 buttons should be showed CLEAR / SAVE, both buttons are shown only when JIRA ID passed validation by pattern
3. When we select from historical list of items and press save - new work item with new hash code is created
4. When the user clicks clear and save - the current work item is unlinked from the current test result
5. Date pattern for historical items should be as follows: Nov 19, 2019 23:20

**Comment by Boniara** [comment]
@lmikhadyuk test it

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.27.RC2 | server v.4.1.81.RC1 | client v.4.1.65.
