### ISSUE TITLE
Zafira patchset inserting test runners is corrupted

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#1875]
**Description**
Zafira patchset inserting additional test runners fails in latest release (4.1.80)

**Steps to reproduce**
1. Install clean Zafira 4.1.79 from scratch
2. Try to update to 4.1.80

**Actual behavior**
Startup fails because of db constraint violation:
```
Caused by: liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "integration_types_name_unique"
  Detail: Key (name)=(SELENIUM) already exists.
  Where: SQL statement "INSERT INTO integration_types(name, display_name, icon_url, integration_group_id) VALUES ('SELENIUM', 'Selenium', '', integration_group_id_var) RETURNING id"
PL/pgSQL function inline_code_block line 25 at SQL statement [Failed SQL: (0) UPDATE integration_groups SET display_name = 'Test Environment Provider' WHERE name = 'TEST_AUTOMATION_TOOL';
```

**Expected behavior (if known)**
Update goes smooth

**Environment**
API (back-end) version: 4.1.80 (check steps!)

**Additional context**
This happens because we updated default test runner and then tried to re-insert Selenium regardless of the fact that it was already there.

Proposed fix: wrap every integration we insert into if else checking if it's already inserted (pseudocode: IF integration_types contains ''selenium" THEN do_nothing ELSE insert selenium). Do that for all integrations we insert just in case.

**Comment by tsvrko** [comment]
done #1879
