### ISSUE TITLE
Message broker integration should be moved to back end app settings

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#1878]
**Description**
Message broker (RabbitMQ) integration should be moved to application settings rather than configured from Integrations UI

**Value**
Message broker currently is a 100% service component for Zafira and has no impact on any of user flows; it should be hidden from user interface and encapsulated as part of back end service implementation.

**Additional context**
From implementation perspective i propose to remove this integration completely (both integration group and type) and move broker settings to `application.yml`.

**Comment by Boniara** [comment]
@lmikhadyuk you can test it using test running on stage, if logs are good - 👍

**Comment by lmikhadyuk** [comment]
@Boniara could you please provide SNAPSHOT version?

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.295-SNAPSHOT | server v.1.468-SNAPSHOT | client v.1.0-SNAPSHOT.
