### ISSUE TITLE
Logo isn't displayed in the left ribbon in Safari/Firefox

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1880]
**Steps to reproduce**
1. Login to Zafira (Admin) in **Safari/Firefox**
2. Click on Project icon
3. Click "Upload new logo"
4. Upload image

**Actual behavior**
Image isn't displayed in the left ribbon.

**Expected behavior **
Image is displayed in the left ribbon.

**Environment**
ui v.1.287-SNAPSHOT | server v.4.1.80 | client v.4.1.64

**Attachments**
<img width="1500" alt="Screen Shot 2019-11-25 at 16 56 35" src="https://user-images.githubusercontent.com/56070333/69546375-b1303080-0fa4-11ea-8823-6a4744d7a309.png">

**Additional context**
**The same issue with Profile logo**

**Comment by danymill** [comment]
Fixed on UI from v. `1.332-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.332-SNAPSHOT | server v.1.507-SNAPSHOT | client v.1.0-SNAPSHOT
