### ISSUE TITLE
Default launchers disappear from the list after scanning 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1881]
**Steps to reproduce**
1. Login to Zafira as admin (new created company)
2. Select test runs tab
3. Click on "launcher button" in the right corner
4. Click on your repository name (There are Carina API and Carina WEB launchers)
5.  Click on settings icon near repository name
6. Click Scan

**Actual behavior**
After scanning there are no Carina API and Carina WEB in the list
<img width="1272" alt="Снимок экрана 2019-10-30 в 21 35 01" src="https://user-images.githubusercontent.com/56070333/69556271-83071c80-0fb5-11ea-9ff0-d9a30d5cddc0.png">

**Environment**
ui v.1.287-SNAPSHOT | server v.4.1.80 | client v.4.1.64
**Attachments**

**Comment by danymill** [comment]
Available on UI from v. `1.295-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.295-SNAPSHOT | server v.1.468-SNAPSHOT | client v.1.0-SNAPSHOT.
