### ISSUE TITLE
One word is displayed in the date filter after selecting date range template

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1893]
**Steps to reproduce**
1. Login to Zafira (Admin or User)
2. Open Test runs tab
3. Select "Last month"/"Last year"/"This week" (date range template) in Date filter

**Actual behavior**
One word is displayed in the filter
<img width="2048" alt="Screen Shot 2019-11-27 at 12 52 25" src="https://user-images.githubusercontent.com/56070333/69713154-1b67e300-1115-11ea-8e11-aaac7016f852.png">

**Expected behavior**
Dates should be displayed in the filter

**Environment**
**Mobile and Desktop** 
ui v.1.290-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT

**Comment by zmutnik** [comment]
Available on UI from v 1.331-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Reproducible on mobile.

**Comment by danymill** [comment]
fixed on UI from v. `1.332-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.332-SNAPSHOT | server v.1.507-SNAPSHOT | client v.1.0-SNAPSHOT.
