### ISSUE TITLE
Scroll doesn't work correctly in test details tab on Mobile

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1894]
**Steps to reproduce**
1. Login to Zafira from **Mobile** (Admin/User)
2. Open test run tab 
3. Open test run
4. Click 3 dots on test
5. Click Details (eye)

**Actual behavior**
Scroll doesn't work correctly in test details. unable to see the last log item (only after repeating scroll) 

**Environment**
**Mobile**
iOS 13.1.3
ui v.1.290-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT

**Comment by danymill** [comment]
Available on UI from v. `1.292-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.293-SNAPSHOT | server v.1.468-SNAPSHOT | client v.1.0-SNAPSHOT.
