### ISSUE TITLE
Chart popup hiding under the chart on mobile

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1895]
**Steps to reproduce**
1. Login to Zafira from Mobile (Admin/User)
2. Open General dashboard
3. Click on share of pie chart

**Actual behavior**
Chart popup hiding under the chart on mobile

**Environment**
Mobile
Safari 
iOS 13.1.3
ui v.1.290-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT

**Attachments**
![IMG_6614](https://user-images.githubusercontent.com/56070333/69735879-7ebc3a00-1142-11ea-8e71-1c3d5064f8d0.PNG)
![IMG_6613](https://user-images.githubusercontent.com/56070333/69735880-7f54d080-1142-11ea-9a21-fd259c73f922.PNG)

**Comment by danymill** [comment]
To solve this issue we need to add extra styles for tooltips (https://echarts.apache.org/en/option.html#tooltip.extraCssText)

@Boniara please add `transform: translateZ(0)`

**Comment by Boniara** [comment]
@danymill all widget template were updated, test it

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.293-SNAPSHOT | server v.1.468-SNAPSHOT | client v.1.0-SNAPSHOT.

**Comment by lmikhadyuk** [comment]
Reproducible on Mobile (Safari/Chrome) in ui v.1.29.RC2 | server v.4.1.82.RC5 | client v.4.1.65.

**Comment by VVmartseniuk** [comment]
fix PR  https://github.com/qaprosoft/zafira/pull/2034

**Comment by okamara** [comment]
Tested. Fixed.
