### ISSUE TITLE
JIRA integration couldn't be enabled by admin user

### ISSUE THREAD

**Issue by rkatuzhanets** [qaprosoft/zafira#1897]
**Steps to reproduce**
User Role: ROLE_ADMIN
Group name: Admins
1. Log in to Zafira
2. Navigate to integrations tab
3. Choose **Test Case Management** chip
4. Click on JIRA toggle switch

**Actual behavior**
JIRA integration should be enabled

**Expected behavior (if known)**
**Unable to change JIRA state** error appears. 

**Environment**
ui v.1.26 
server v.4.1.80
client v.4.1.64

**Attachments**
<img width="566" alt="jiraIntegrationIssue" src="https://user-images.githubusercontent.com/21850997/69763129-3d954b80-117d-11ea-9351-b0e52ea234cf.png">
<img width="454" alt="console" src="https://user-images.githubusercontent.com/21850997/69763235-8cdb7c00-117d-11ea-968f-a3eae769e163.png">
<img width="891" alt="network" src="https://user-images.githubusercontent.com/21850997/69763237-906f0300-117d-11ea-8005-f009839fe3a3.png">

**Comment by tsvrko** [comment]
@rkatuzhanets seems like jira is misconfigured, it's necessary to wipe out all settings from db.

**Comment by lmikhadyuk** [comment]
Was not able to reproduce in ui v.1.327-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT.
