### ISSUE TITLE
User is able to look through all dashboards through the links

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1898]
**Steps to reproduce**
[Make sure to specify user role used to log in to Zafira]
Below are the steps to reproduce the behavior:
1. Login to Zafira (User)
2. Open Dashboard (for example General)
3.  Change dashboard id

**Actual behavior**
User is able to look through all dashboards through the links (has no permissions to dashboards)

**Environment**
ui v.1.291-SNAPSHOT | server v.1.464-SNAPSHOT | client v.4.0.33-SNAPSHOT

**Comment by danymill** [comment]
@nsidorevich @Boniara Looks like this should be handled on BE side, and the FE will handle appropriate response.

**Comment by Boniara** [comment]
Will be available on be version > 1.535-SNAPSHOT

**Comment by danymill** [comment]
Fixed on UI from v. `1.361-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.362-SNAPSHOT | server v.1.541-SNAPSHOT | client v.1.0-SNAPSHOT
