### ISSUE TITLE
User is not able to delete test run from mobile 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1909]
**Steps to reproduce**
1. Login to Zafira (Admin/User) from Mobile
2. Open test run tab
3. Open test run
4. Click on details (eye) on test
5. Go out details window
6. Click on 3 dots on test run
7. Select Delete

**Actual behavior**
User is not able to delete test run from mobile 

**Expected behavior**
User is able to delete test run from mobile

**Environment**
ui v.1.27.RC1 | server v.4.1.81.RC1 | client v.4.1.65
safari
IOS 13.1.3

**Comment by Boniara** [comment]
IOS only

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.24-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT.
