### ISSUE TITLE
User is not able to scan new repo 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1910]
**Steps to reproduce**
1. Login to Zafira (Admin/User)
2. Open test run tab
3. Click "Test Launcher" button in the right corner
4. Click "Add repo" button
5. Select Organization from dropdown list
6. Select Repository from dropdown list
7. Click "Add" button
8. Close window
9. Click "Test Launcher" button in the right corner
10. Click on settings button near new empty launcher

**Actual behavior**
Nothing happens

**Expected behavior**
"Choose automation server" window appears

**Environment**
ui v.1.27.RC2 | server v.4.1.81.RC1 | client v.4.1.65

**Comment by danymill** [comment]
fixed on UI from v. `1.27.RC3`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.27.RC4 | server v.4.1.81.RC1 | client v.4.1.65.
