### ISSUE TITLE
Zafira demo is not opened by url -> http://demo.qaprosoft.com/zafira

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1914]
**Description**
Zafira demo is not opened by url -> http://demo.qaprosoft.com/zafira

**Steps to reproduce**
[Make sure to specify user role used to log in to Zafira]
Below are the steps to reproduce the behavior:
1. Go to http://demo.qaprosoft.com/zafira in browser
Actual result: 404 error appears on the page

**Expected behavior (if known)**
Page is opened by the url without errors

**Environment**
zafira demo env.

**Comment by nsidorevich** [comment]
@okamara Zafira in browser resides under /app path. There's no handler for /zafira which result into 404.
