### ISSUE TITLE
A test method must be registered for each individual suite

### ISSUE THREAD

**Issue by katedkm** [qaprosoft/zafira#1929]
**Description**
When we review statistic info about stability of special test case we want to see suites list that include this test case in a 'TESTCASE INFO' widget.
<img width="856" alt="Screen Shot 2019-12-06 at 16 34 33" src="https://user-images.githubusercontent.com/43830416/70327661-5cb06f00-1848-11ea-9e5b-f49ab0f92093.png">

For now If we create a dashboard with tests failures statistic info for a project, the suite name may not match with the suite name in 'TESTCASE INFO' widget (detailed widget with info for special test case). It's applicable for projects with cross browsers/platforms testing.

**Value**
It will help to see more detailed and correct information about special test case. It is really actual for projects where cross browsers/platforms testing is used.

**Comment by katedkm** [comment]
@vdelendik Could you take a look, please?

**Comment by hursevich** [comment]
@vdelendik, do we need to change db for that ticket?

**Comment by vdelendik** [comment]
@hursevich @katedkm fixed in 4.1.67 zafira-client.
