### ISSUE TITLE
Unable to register selenium/mcloud/etc. in zafira 

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1932]
**Description**
Open Integration and try to register zafira, browsersack, mcloud, ZEBRUNNER, etc.
Integration is always red except ZEBRUNNER

Unable to register selenium in zafira:
http://demo:demo@demo.qaprosoft.com/ggr/wd/hub

hub works fine for example of default quota: http://demo:demo@demo.qaprosoft.com/quota
But mcloud intergation is always red

<img width="1438" alt="Screen Shot 2019-12-06 at 9 34 17 PM" src="https://user-images.githubusercontent.com/32964663/70349645-30abe280-1876-11ea-8b3a-4274c64f3ff0.png">

**Comment by nsidorevich** [comment]
@okamara please specify environment, expected and actual behavior. Are you sure that you are using right hostnames/credentials? And what do you mean by "always red" mcloud integrations? Always when? Add details please.

**Comment by okamara** [comment]
@nsidorevich  -> Zafira versions: ui v.1.27 | server v.4.1.81 | client v.4.1.64
Example for selenium:
<img width="428" alt="Screen Shot 2019-12-12 at 4 44 13 PM" src="https://user-images.githubusercontent.com/32964663/70717280-143cf980-1cff-11ea-9983-f859266d4827.png">

**Comment by vdelendik** [comment]
We have to improve hubs verification algorithm testing credentials as well. Also some providers don't provide valid response for /wd/hub in security purposes.
So to mark integration as green any of below condition should be ok:
1) 200 status for provided the URL as is using credentials for auth
2) if above in 404 we have to try to do the same call but replacing "/wd/hub" by "/quota"
3) for browserstack let's use another way ignoring hub url (additional enhancement will be submitted to prepopulate valid hosts for well-known providers aka zebrunner).
https://user:@password@www.browserstack.com/automate/plan.json

i.e. 
http://user:password@demo.qaprosoft.com:4444/wd/hub - 200 status
or
http://user:password@demo.qaprosoft.com:4444/quota - 200 status

browserstack:
https://user:@password@www.browserstack.com/automate/plan.json - 200 status

**Comment by Boniara** [comment]
will be available in 4.1.82 version

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.29.RC2 | server v.4.1.82.RC5 | client v.4.1.65.
