### ISSUE TITLE
Allow to mark as failed tests in skipped, aborted statuses

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/zafira#1934]
**Description**
Unable to mark test as failed in status skipped, aborted etc. 

**Steps to reproduce**
1. Open test runs
2. Open results of any failed test run
3. Try to mark test as failed if it is in skipped, aborted etc. status

**Actual behavior**
Only mark as passed is available.

**Expected behavior (if known)**
Mark as passed / failed is expected.

**Environment**
[Make sure to specify Zafira versions you see at login page]
UI version: ui v.1.27
API (back-end) version: server v.4.1.81

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.19-SNAPSHOT | server v.1.475-SNAPSHOT | client v.1.0-SNAPSHOT.
