### ISSUE TITLE
After declare job types via xml, launchers stop working correctly

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1935]
**Description**
After declare job types via ios and android xml launchers stop working correctly.
job types:
android-web
ios-web
e.g.
<parameter name="jenkinsJobType" value="ios-web"/>

**Steps to reproduce:**
1. Open ios.xml 
2. Change jenkinsJobType value to "ios-web"
3. Commit changes to test repo "capabilities_field"
4. In Jenkins run onPush job for test repo "capabilities_field"
5. Open Zafira Launcher and select ios in the list

**Actual result:** 
None radio-button is set 

**Expected:** 
ios radio-button is set 

<img width="860" alt="Screen Shot 2019-12-09 at 6 23 41 PM" src="https://user-images.githubusercontent.com/32964663/70448607-a780ef80-1ab1-11ea-8801-352b3323d30d.png">
<img width="962" alt="Screen Shot 2019-12-09 at 6 22 56 PM" src="https://user-images.githubusercontent.com/32964663/70448622-abad0d00-1ab1-11ea-9af4-83222fe9eaf8.png">
<img width="975" alt="Screen Shot 2019-12-09 at 6 22 49 PM" src="https://user-images.githubusercontent.com/32964663/70448640-afd92a80-1ab1-11ea-9411-fcdf070facb3.png">

**Comment by tsvrko** [comment]
To be clear for the tests with postfix **-web** *web* radiobutton should be chosen by default. @danymill probably *job_type* ios-web/android-web is not parsed correctly on UI?

**Comment by danymill** [comment]
fixed on UI from v. `1.357-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
@okamara could you please check this issue

**Comment by okamara** [comment]
Fixed. Tested on 1.360-SNAPSHOT
