### ISSUE TITLE
Process of incorrect scan in launchers stopped by time-out only

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1936]
**Description**
Process of incorrect scan in launchers stopped by time-out only. Need to stop this process with correct message

**Steps to reproduce**

1. Go to zafira Launchers
2. Tap rescan for incorrect repo e.g. "capabilities_file"
3. Tap Re-Scan

**Actual behavior**
User wait for 2+ mins. It looks like endless process.

**Expected behavior (if known)**
Need to stop this process with correct message

**Environment**
http://54.193.74.120/app

<img width="887" alt="Screen Shot 2019-12-09 at 6 44 22 PM" src="https://user-images.githubusercontent.com/32964663/70451577-aa321380-1ab6-11ea-9304-dee0f0b33b59.png">

**Comment by nsidorevich** [comment]
@okamara why do you mean by "incorrect repo"?

**Comment by okamara** [comment]
zafira version: ui v.1.27 | server v.4.1.81 | client v.4.1.64
In my as example QA made a mistake in repo name and write "test_file" instead of "test_slash". "test_file" repo is not exist.

**Comment by nsidorevich** [comment]
@Boniara let's see what can be done on our end from back-end perspective - we should either timeout after some reasonable wait time or see what kind of response we get from GitHub

**Comment by tsvrko** [comment]
Cause of crash was incorrect branch name, not repo, fixed and available on stage env.

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.19-SNAPSHOT | server v.1.475-SNAPSHOT | client v.1.0-SNAPSHOT.
