### ISSUE TITLE
default integration settings script is not up-to-date

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1937]
https://github.com/qaprosoft/zafira/blob/dd45df28ad4a610d9b89a1efb50d8dbe19d35e62/database/zafira-init.sh#L21

psql --username $POSTGRES_USER -c "UPDATE zafira.SETTINGS SET VALUE='$ZAFIRA_AMAZON_ENABLED' WHERE NAME='AMAZON_ENABLED';"

we don't use settings table anymore for default integrations. need updates in zafira-init.sh for default integrations based on latest changes

**Comment by nsidorevich** [comment]
Additional context: this change can be reproduced with standalone Zafira deployment when Zafira schema is initialized from scratch. `db-app-data.sql` does not contain those default integrations and as a result we lost those when moved integrations from `settings` to `integration-*` tables

**Comment by nsidorevich** [comment]
Should be fixed in latest snapshot versions and will be available out of the box in next release version (4.1.83)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/zafira/pull/1945
