### ISSUE TITLE
Zafira+slack integration doesn't work in some ways properly

### ISSUE THREAD

**Issue by katedkm** [qaprosoft/zafira#1940]
**Description**
Comment for tests result report in Zafira doesn't send to a corresponding slack channel.
When you try to send a comment to a slack channel as 'Mark as reviewed', it doesn't appear in a corresponding channel.

**Steps to reproduce**
Below are the steps to reproduce the behavior:
1. Go to Zafira reporting portal;
2. Choose any test result report that has integration with the slack;
3. Click on the test run card cell menu that take place on it's right side;
4. Click on 'Mark as reviewed' menu item;
5. Type a text in comment field, e.g. 'Reviewed';
6. Click on 'Mark as reviewed' button;
7. Check the test run results with your comment in corresponding slack channel.

**Actual behavior**
The test run results with your comment doesn't appear in slack channel.

**Expected behavior (if known)**
Commented test run result in Zafira has reached the needed channel.

**Environment**
ui v.1.27 | server v.4.1.81 | client v.4.1.64

**Comment by nsidorevich** [comment]
@lmikhadyuk should be available in 1.477-SNAPSHOT and newer.

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.19-SNAPSHOT | server v.1.476-SNAPSHOT | client v.1.0-SNAPSHOT.
