### ISSUE TITLE
Get by non-existing launcher id does not return status code 404

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#1941]
**Description**
When we send get launcher by id request and pass non-existing id, response with status code 200 and with empty response body appears.

**Steps to reproduce**
1. choose any id that you don't have in your tenant. f.i. 800
2. authorize in Zafira API
3. send GET request to https://testtennant.qaprosoft.farm/zafira-ws/api/launchers/800 and specify Bearer token in headers

**Actual behavior**
HTTP/1.1 200 
Server: nginx/1.13.12
Date: Fri, 13 Dec 2019 14:53:53 GMT
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, PUT, UPDATE, OPTIONS, DELETE
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Accept-Language, Authorization, Access-Token, FileType
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=15724800; includeSubDomains

**Expected behavior (if known)**
status code 404 in response is expected

**Environment**
https://testtennant.qaprosoft.farm/zafira-ws/api
API (back-end) version: 2

**Comment by tsvrko** [comment]
fixed #1941, available in 1.478-SNAPSHOT and in upcoming 4.1.82 release

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.309-SNAPSHOT | server v.1.478-SNAPSHOT | client v.1.0-SNAPSHOT.
