### ISSUE TITLE
hub integrations: prepopulate well known urls

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1942]
Let's register default selenium hub urls for well known providers, i.e.:
zebrunner: https://hub.zebrunner.com/wd/hub
aerokube: https://browsers.aerokube.com:4444/wd/hub
browserstack: https://hub-cloud.browserstack.com/wd/hub
saucelabs: http://ondemand.saucelabs.com:80/wd/hub

So when user want to enable something it should see above url values prepopulated and be able to insert only credentials

**Comment by nsidorevich** [comment]
This one is not going to be implemented in short term perspective for sure because of the way integrations are processed by application. Either all mandatory params should be in place (meaning dummy values for username and password) or none of them should be there.
