### ISSUE TITLE
In case of video player is disabled, then it should not be displayed on zafira reports

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/zafira#1943]
Incase below property is mentioned, the video player should not be displayed.
capabilities.enableVideo=false

Currently, it shows in disabled format. It should not be displayed.

**Comment by Boniara** [comment]
will be available in 1.29 release

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.29.RC2 | server v.4.1.82.RC5 | client v.4.1.65.
