### ISSUE TITLE
Add support for LambdaTest integration

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/zafira#1952]
**Description**
Let's add LambdaTest into test environment integration. 
Integration params:
- URL
- username
- password

Connectivity check endpoint: https://api.lambdatest.com/automation/api/v1/platforms + Basic auth (username + password)

**Value**
Expands support of 3rd party services.

**Additional context**
None

**Comment by nsidorevich** [comment]
@hursevich link on their API docs? My understanding is that it is no different in terms of params from integrations we already have, but we need to understand what would be the right way to check connectivity. Thanks

**Comment by nsidorevich** [comment]
Done and available in Zafira 4.1.82 or later.
