### ISSUE TITLE
launcher with preset can't be deleted 

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#1963]
**Description**
When we try delete launcher by id with created preset for it we can't do it and have response status code 500.

**Steps to reproduce**
1. authorize in Zafira API
2. create launcher and get laucherId
send Post request to https://automation.qaprosoft.farm/zafira-ws/api/launchers?automationServerId=${automationServerId}
3. create preset with help laucnherId
send Post request to https://automation.qaprosoft.farm/zafira-ws/api/launchers/${launcherId}/presets
4. send Delete request to https://automation.qaprosoft.farm/zafira-ws/api/launchers/%{launcherId} and specify Bearer token in headers

**Actual behavior**
HTTP/1.1 500 
Server: nginx/1.13.12
Date: Fri, 20 Dec 2019 07:42:44 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, PUT, UPDATE, OPTIONS, DELETE
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Accept-Language, Authorization, Access-Token, FileType
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=15724800; includeSubDomains

**Expected behavior (if known)**
status code 200 in response and deleting launcher

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.344-SNAPSHOT | server v.1.528-SNAPSHOT | client v.1.0-SNAPSHOT.
