### ISSUE TITLE
The wrong number of recipients is displayed when sending the email

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1967]
**Steps to reproduce**
1. Login to Zafira 
2. Open test runs tab
3. Click on 3 dots on test run
4. Select Send as email
5. Entrer valid email
6. Click Send  

**Actual behavior**
The number of recipients is 20
https://www.dropbox.com/s/l6pv04dgvex4c3o/recipients.mp4?dl=0

**Expected behavior**
The number of recipients is equal to the number of entered emails

**Environment**
ui v.1.317-SNAPSHOT | server v.1.486-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by danymill** [comment]
fixed on UI from v. `1.330-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.330-SNAPSHOT | server v.1.494-SNAPSHOT | client v.1.0-SNAPSHOT.
