### ISSUE TITLE
Checkboxes disappear from test runs tab after selecting on mobile

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1972]
**Steps to reproduce**
1. Login to Zafira from mobile 
2. Open test runs tab
3. Select checkboxes

**Actual behavior**
Checkboxes disappear after selecting
![IMG_6992](https://user-images.githubusercontent.com/56070333/71479189-6b18f780-2804-11ea-834c-9f4d9438816b.PNG)

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Environment**
ui v.1.325-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT
Iphone 8
iOS 13.1.3

**Comment by zmutnik** [comment]
Available on UI from v 1.329-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.330-SNAPSHOT | server v.1.494-SNAPSHOT | client v.1.0-SNAPSHOT.
