### ISSUE TITLE
Enabled integrations should be displayed first in integration groups

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#1973]
**Description**
We should display enabled integrations first so integrations UI will look pretties and UX will be better.

**Additional context**
The way it is now:
![Screen Shot 2019-12-26 at 5 48 16 PM](https://user-images.githubusercontent.com/8956214/71480076-68200600-2808-11ea-8d41-f8f5571c4492.png)

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.327-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT
