### ISSUE TITLE
Fab button doesn't disappear while scrolling on mobile 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1976]
**Steps to reproduce**
1. Login to Zafira from mobile
2. Open test runs tab
3. Select checkboxes
4. scroll down

**Actual behavior**
Fab button doesn't disappear while scrolling

**Expected behavior**
Fab button disappears while scrolling 

**Environment**
ui v.1.24-SNAPSHOT | server v.1.489-SNAPSHOT | client v.1.0-SNAPSHOT
mobile 
iOS 13.1.3

**Comment by zmutnik** [comment]
Available on UI from v 1.329-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.330-SNAPSHOT | server v.1.494-SNAPSHOT | client v.1.0-SNAPSHOT.
