### ISSUE TITLE
Repositories are not loaded in Test Launcher 

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1977]
**Description**

**Steps to reproduce**
[Make sure to specify user role used to log in to Zafira]
Below are the steps to reproduce the behavior:
1. Go to Zafia
2. Click on Launcher button
3. Click TestLauncher button 
4. Click Add Repo
5.Tapp on organization
 

**Actual behavior**
Repo is not loaded in the dropdown list. There are error in console(see image in attachment)

**Expected behavior (if known)**
All available repo are in the dropdown list

**Environment**
 Zafira versions: 4.1.83 and 1.30

**Attachments**
<img width="1440" alt="Screen Shot 2019-12-27 at 5 08 25 PM" src="https://user-images.githubusercontent.com/32964663/71520442-2ad17c00-28cd-11ea-8476-ff0d2f8cfa7e.png">

**Comment by nsidorevich** [comment]
Fixed in zafira-ui:1.31
