### ISSUE TITLE
If test is invoked in local and stopped in between, It still shows in progress on zafira test runs

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/zafira#1980]
**Prerequisite**
1. Carina framework should be deployed as a local machine.
2. Zafira reporting server should be deployed as a server machine.
3. Connectivity is done in between Carina and Zafira. 

**Description**
If a test is invoked in local and stopped in between, It still shows in progress on a Zafira test runs

**Steps to reproduce**
1. Go to local machine and invoke any of test from testng_suites.
2. Stop the test from a local machine in between.
3. Check the status on a Zafira reporting server.

**Actual behavior**
Zafira test runs show status as in-progress and It shows pending on test dashboard.

**Expected behavior (if known)**
I think if the test is stopped on local it should also flag on the Zafira reporting server so that runs should also show status as stopped and It gives correct implementation.

**Comment by prasadjshimpi** [comment]
[
![zafira_1980](https://user-images.githubusercontent.com/31615407/71709000-bb064880-2e1a-11ea-8d1e-b1362adde135.png)
](url)

**Comment by nsidorevich** [comment]
For more details see #1983

**Comment by nsidorevich** [comment]
This is something that cannot be done on client side since on force kill of java process no graceful shutdown flow would be possible. We might come up with some sort of detection of such hanging runs on Zafira side though. 
Closing this one.
cc: @vdelendik
