### ISSUE TITLE
Zafira shows status In Progress for aborted jobs in Jenkins

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#1983]
**Description**
Zafira shows status In Progress for aborted jobs in Jenkins

**Steps to reproduce**
Make sure to specify user role used to log in to Zafira - QA okamara

Below are the steps to reproduce the behavior:
1. Start Test Run via Zafira
2. Job was aborted due to Crash 
3. Verify status of aborted Job in Zafira and Jenkins

**Actual behavior**
Zafira shows status In Progress for aborted jobs in Jenkins

**Expected behavior (if known)**
Show correct status in Zafira for aborted jobs in Jenkins

**Environment**
https://snc.zebrunner.com/

**Comment by nsidorevich** [comment]
Duplicates https://github.com/qaprosoft/zafira/issues/1980
cc: @okamara

**Comment by nsidorevich** [comment]
Closing this one in favor of #1980. Gonna track in back there.
