### ISSUE TITLE
Zafira API returns 500 error response on test case creation attempt

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#1988]
**Description**
Zafira API returns 500 error response on test case creation attempt

**Steps to reproduce**
Login as any user and obtain auth token.
Below are the steps to reproduce the behavior:
1. Send POST to `/api/tests/cases` with following payload:
```
{
  "info": "string",
  "primaryOwnerId": 0,
  "testClass": "string",
  "testMethod": "string",
  "testSuiteId": 0
}
```

**Actual behavior**
500 error code is returned with no details on error.

**Expected behavior (if known)**
Proper error response is returned with 404 error code

**Environment**
API (back-end) version: 4.1.83

**Comment by Boniara** [comment]
Will be available in 1.507-SNAPSHOT
