### ISSUE TITLE
There are 2 emailList fields in build now window

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1990]
**Steps to reproduce**
1. Login to Zafira
2. Open test runs tab
3. Click on "test launcher" button in the right corner
4. Expand "carina-demo" launcher 
5. Select "Carina-Demo-Regression-Pipeline"
6. Enter valid email
7. Click on "launch" button
8. Click on 3 dots on test run
9. Select Build now

**Actual behavior**
There are 2 emailList fields
<img width="1942" alt="Screen Shot 2020-01-09 at 12 15 25" src="https://user-images.githubusercontent.com/56070333/72054482-1a140380-32da-11ea-8cfc-16dd5c641c0e.png">

**Environment**
ui v.1.331-SNAPSHOT | server v.1.504-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by danymill** [comment]
UI displays what it gets from BE. @nsidorevich Please reassign appropriate BE developer. Thx.
![image](https://user-images.githubusercontent.com/6594800/74335117-81771480-4dac-11ea-9aad-ed47c5837c5e.png)

**Comment by nsidorevich** [comment]
@Boniara please take a look while we send the same attribute twice.

**Comment by Boniara** [comment]
This bug is connected with our repo registration pipeline.
@tsvrko, @vdelendik could you investigate the issue?

**Comment by Boniara** [comment]
@vdelendik provided in corresponding project
