### ISSUE TITLE
Launcher window displays wrong information after switching between repositories 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1991]
**Steps to reproduce**
1. Login to Zafira (Admin or User)
2. Open test run tab
3. Click "Test Launcher" button in the right corner
4. Click "Add repo" button
5. Select Organization from dropdown list
6. Select Repository from dropdown list
7. Click "Add" button
8. Click on (+) button near added repo
9. Click on carina-demo

**Actual behavior**
Create launcher manually appears
<img width="1262" alt="Screen Shot 2020-01-09 at 13 08 47" src="https://user-images.githubusercontent.com/56070333/72058556-56972d80-32e1-11ea-9e96-d1168bb5916f.png">

**Expected behavior**
<img width="1146" alt="Screen Shot 2020-01-09 at 13 16 46" src="https://user-images.githubusercontent.com/56070333/72059205-9e6a8480-32e2-11ea-9a2e-21c098e195a4.png">

**Environment**
ui v.1.331-SNAPSHOT | server v.1.504-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by danymill** [comment]
fixed on UI from v. `1.332-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.332-SNAPSHOT | server v.1.507-SNAPSHOT | client v.1.0-SNAPSHOT.
