### ISSUE TITLE
Test with invalid link in artifacts is not displayed in test run

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#1993]
**Pre-conditions**
Authorization.
Test suite, test run, job and test case were created

**Steps to reproduce**
Send POST to  **/api/tests/{id}/artifacts** with invalid link in body
{
  "expiresIn": 0,
  "id": 0,
  "link": "string",
  "name": "string",
  "testId": 0
}

**Actual behavior**
Test is not displayed in test run

**Environment**
ui v.1.331-SNAPSHOT | server v.1.504-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by danymill** [comment]
fixed on UI from v. `1.332-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.332-SNAPSHOT | server v.1.507-SNAPSHOT | client v.1.0-SNAPSHOT.
