### ISSUE TITLE
Endpoints with ID's placeholder in Swagger UI is unworking (launcher-controller, test-run-controller, test-controller)

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#1994]
**Description**
When we try use some Swagger UI endpoints  that needs ID (f. e. launcherId, testRunId, testId) we can't retrieve response or status code (issue with ID's placeholder)

**Steps to reproduce**

1. authorize in Zafira API
2. create launcher and get laucherId
send Post request to https://automation.qaprosoft.farm/zafira-ws/api/launchers?automationServerId=${automationServerId}
3. Try to input launcher id (id placeholder) in get launcher by id method (Swagger UI)
4. tap execute btn

**Actual behavior**
 (ID's placeholder turn red, execute btn is not clickable)

**Expected behavior (if known)**
status code 200 in response and getting launcher

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by tsvrko** [comment]
Looks like swagger bug. Does it work after page refresh?

**Comment by khsboris** [comment]
> Looks like swagger bug. Does it work after page refresh?

No, all ID's placeholder is unworking all time, after page refresh too

**Comment by tsvrko** [comment]
For now looks like you should execute requests in postman for now.

**Comment by Boniara** [comment]
@tsvrko try to update with dataTypeClass = Long.class (e.g.). It is working

**Comment by tsvrko** [comment]
Fixed, available on stage ui v.1.360-SNAPSHOT | server v.1.535-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.360-SNAPSHOT | server v.1.537-SNAPSHOT | client v.1.0-SNAPSHOT
