### ISSUE TITLE
Delete test by non-existent testId does not return status code 404

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#1998]
**Description**
When we send delete test by testId request and pass non-existent id, we have response with status code 200.

**Steps to reproduce**

1. authorize in Zafira API
2. choose any id that you don't have, f.e. 1000
3. send DELETE request to automation.qaprosoft.farm/zafira-ws/api/tests/1000

**Actual behavior**
HTTP/1.1 200 
Server: nginx/1.13.12
Date: Mon, 13 Jan 2020 14:36:36 GMT
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, PUT, UPDATE, OPTIONS, DELETE
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Accept-Language, Authorization, Access-Token, FileType
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=15724800; includeSubDomains

**Expected behavior (if known)**
status code 404 in response 

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by tsvrko** [comment]
Available on stage env ui v.1.34.RC6 | server v.1.532-SNAPSHOT @lmikhadyuk

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.34.RC6 | server v.1.532-SNAPSHOT | client v.1.0-SNAPSHOT.
