### ISSUE TITLE
Retrieves test work items with non-existent testId does not return status code 404

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#2000]
**Description**
When we send get work items request and pass non-existent id, we have response with status code 200.

**Steps to reproduce**

1. authorize in Zafira API
2. choose any id that you don't have or deleted later, f.e. 1000
3. chose any work item's type: TASK/BUG/COMMENT/EVENT
4. send GET request to automation.qaprosoft.farm/zafira-ws/api/tests/1000/workitem/{your_type}

**Actual behavior**
Status code 200 and empty array in response

**Expected behavior (if known)**
status code 404 in response

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by tsvrko** [comment]
Available on stage env ui v.1.34.RC6 | server v.1.532-SNAPSHOT @lmikhadyuk

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.34.RC6 | server v.1.532-SNAPSHOT | client v.1.0-SNAPSHOT.
