### ISSUE TITLE
Upgrade Spring Boot to 2.2.4

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#2005]
**Description**
Let's stay up to date with latest release versions to avoid upgrade issues in future.

**References**
https://spring.io/blog/2020/01/20/spring-boot-2-2-4-released

**Comment by tsvrko** [comment]
Available in ui v.1.34.RC1 | server v.4.1.86.RC1

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.34.RC6 | server v.4.1.86.RC2 | client v.1.0-SNAPSHOT.
