### ISSUE TITLE
Upgrade Gradle to 6.1

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#2006]
**Description**
6.1 has been released recently - let's stay up to date with latest version.

**References**
https://gradle.org/releases/

**Comment by nsidorevich** [comment]
6.1.1 was released. Use this one

**Comment by tsvrko** [comment]
Available in ui v.1.34.RC1 | server v.4.1.86.RC1

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.34.RC6 | server v.4.1.86.RC2 | client v.1.0-SNAPSHOT.
