### ISSUE TITLE
Add 'tvOS' platform to jenkinsJobType

### ISSUE THREAD

**Issue by pkebets** [qaprosoft/zafira#2007]
Add the 'tvOS' platform to jenkinsJobType to correctly display AppleTV tests

**Comment by tsvrko** [comment]
We already have **appletv** and **androidtv** platform icons available, maybe you could use *appletv* as platform? This way you'll have icon and tvos tests won't be confused with androidtv tests.

**Comment by tsvrko** [comment]
Shifted to appletv usage
