### ISSUE TITLE
Get group by Id=3 (Users) get incorrect response

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#2015]
**Description**
Get group by Id=3 (Users) get response without new created users

**Steps to reproduce**

1. authorize in Zafira API
2. create new user
send PUT request to https://automation.qaprosoft.farm/zafira-ws/api/users
3. Check that user was added to goupId = 3 and 
send GET request to https://automation.qaprosoft.farm/zafira-ws/api/groups/all?isPublic=true&public=true
4. send request GET to https://automation.qaprosoft.farm/zafira-ws/api/groups/3 
Check that new user was not find

**Actual behavior**
 status code 200 but get response without new created users

**Expected behavior (if known)**
status code 200 and get response with new created users

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by Boniara** [comment]
Will be available in 1.528-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.344-SNAPSHOT | server v.1.528-SNAPSHOT | client v.1.0-SNAPSHOT.
