### ISSUE TITLE
Group is created even if Zafira API returns 500 error response

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#2016]
**Steps to reproduce**
1. Authorize in Zafira API
2. Send POST request to automation.qaprosoft.farm/zafira-ws/api/groups
    BODY: {
  "users": [],
  "name": "test12345",
  "role": "ROLE_USER",
  "permissions": [
    {
      "id": 1
    }
  ]
}

**Actual behavior**
Response: 500 Internal Server Error. But group is created.

**Environment**
ui v.1.344-SNAPSHOT | server v.4.1.85.RC2 | client v.1.0-SNAPSHOT

NOTE:"name" in permissions is required

**Comment by Boniara** [comment]
Will be available in 1.528-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.344-SNAPSHOT | server v.1.528-SNAPSHOT | client v.1.0-SNAPSHOT.
