### ISSUE TITLE
Get all launchers (or get launcher by Id) get response without launchers presets

### ISSUE THREAD

**Issue by khsboris** [qaprosoft/zafira#2030]
**Description**
Get all launchers or get launcher by Id get response without created presets for launchers ("presets": null)

**Steps to reproduce**
1. authorize in Zafira API
2. Get jobId 
3. Create new launcher
send POST request to https://automation.qaprosoft.farm/zafira-ws/api/launchers
4. Create preset
send POST request to https://automation.qaprosoft.farm/zafira-ws/api/launchers/launcherId/presets
5. Get launcher by id (get all launchers) 
send GET request to https://automation.qaprosoft.farm/zafira-ws/api/launchers/launcherId
and check that field "presets"= null

**Actual behavior**
field "presets"=null in GET response

**Environment**
https://automation/zafira-ws/api
API (back-end) version: 2

**Comment by Boniara** [comment]
Will be available in 1.535-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.360-SNAPSHOT | server v.1.535-SNAPSHOT | client v.1.0-SNAPSHOT
