### ISSUE TITLE
Reports are not sent to emails

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/zafira#2033]
Nobody gets test runs reposts by email.

**Environment**
ui v.1.34 | server v.4.1.86 | client v.4.1.65

**logs from Jenkins**
`13:19:05  HttpMethod: POST
13:19:05  URL: https://***.zebrunner.com/zafira-ws/api/tests/runs/304765fc-8b01-48a9-b5ea-ee7f8368e505/email?filter=all
13:19:05  Content-type: application/json
13:19:05  Authorization: *****
13:19:05  Sending request to url: https://***.zebrunner.com/zafira-ws/api/tests/runs/304765fc-8b01-48a9-b5ea-ee7f8368e505/email?filter=all
13:19:06  Response Code: HTTP/1.1 500 
[Pipeline] echo
13:19:06  java.lang.IllegalStateException: hudson.AbortException: Fail: the returned code 500 is not in the accepted range: [[200‥401]]
13:19:06    at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:218)
13:19:06    at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:75)
13:19:06    at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
13:19:06    at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:336)
13:19:06    at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:318)
13:19:06    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
13:19:06    at hudson.security.ACL.impersonate(ACL.java:290)
13:19:06    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
13:19:06    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:19:06    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:19:06    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:19:06    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:19:06    at java.lang.Thread.run(Thread.java:748)
Collapse`

**Comment by tsvrko** [comment]
Available on stage env ui v.1.34.RC6 | server v.1.532-SNAPSHOT @lmikhadyuk

**Comment by lmikhadyuk** [comment]
Verified in ui v.1.34.RC6 | server v.1.532-SNAPSHOT | client v.1.0-SNAPSHOT
