### ISSUE TITLE
User is able to enter negative number in thread_count field 

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#2036]
**Description**

**Steps to reproduce**
1. Login to Zafira
2. Open test runs tab
3. Click test launcher in the right corner
4. Click on + (Create launcher manually) near name of repo
5. Enter name and select platform (for example API)
6. Click create 

**Actual behavior**
thread_count field has arrows. User is able to enter negative number.
In another thread_count fields there are no arrows
<img width="1859" alt="Screen Shot 2020-02-13 at 16 39 16" src="https://user-images.githubusercontent.com/56070333/74440678-7e008d80-4e7f-11ea-89d0-2de45566a3c3.png">

**Environment**
ui v.1.357-SNAPSHOT | server v.1.532-SNAPSHOT | client v.1.0-SNAPSHOT
Safari+Chrome

**Comment by MitskevichVS** [comment]
fixed from UI version 1.372-SNAPSHOT

**Comment by lmikhadyuk** [comment]
0 appears in the email_list field. ui: 1.373-SNAPSHOT
server: 1.557-SNAPSHOT
client: 1.0-SNAPSHOT<img width="885" alt="Screen Shot 2020-02-26 at 11 36 39" src="https://user-images.githubusercontent.com/56070333/75326824-60bebc80-588c-11ea-9d15-ade28eed4a88.png">

**Comment by MitskevichVS** [comment]
fixed from UI version 1.377-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.33-SNAPSHOT server: 1.565-SNAPSHOT client: 1.0-SNAPSHOT.
