### ISSUE TITLE
There are 2 tutorials tooltips in the bottom of the page

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#2044]
**Steps to reproduce**
1. Login to Zafira
2. Open General dashboard
3. Open Test runs tab
4. Switch toggle on Sessions
5. Switch toggle on Tests

**OR**
1. Open General dashboard
2. Open Test runs tab
3. Open General dashboard

**Actual behavior**
There are 2 tutorials tooltips in the bottom of the page

**Environment**
ui v.1.360-SNAPSHOT | server v.1.537-SNAPSHOT | client v.1.0-SNAPSHOT

**Attachments**
<img width="1280" alt="Screen Shot 2020-02-17 at 16 06 21" src="https://user-images.githubusercontent.com/56070333/74658234-e06ccd00-51a2-11ea-84cf-06706175052f.png">

**Comment by DmitryMishin** [comment]
fixed on UI from v. `1.377-SNAPSHOT`

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.33-SNAPSHOT server: 1.565-SNAPSHOT client: 1.0-SNAPSHOT.
