### ISSUE TITLE
Different design for search for test runs and test sessions

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#2048]
**Steps to reproduce**
1. Create a new company
2. Login to Zafira
3. Open test runs tab
4. Switch toggle on

**Actual behavior**
Different design for search for test runs and test sessions
<img width="2036" alt="Screen Shot 2020-02-18 at 12 43 44" src="https://user-images.githubusercontent.com/56070333/74724615-8d9c1f80-524d-11ea-95f5-dd9ecf3afe70.png">
<img width="2045" alt="Screen Shot 2020-02-18 at 12 43 55" src="https://user-images.githubusercontent.com/56070333/74724621-8f65e300-524d-11ea-85d2-c91c72528a21.png">

**Environment**
ui v.1.360-SNAPSHOT | server v.1.539-SNAPSHOT | client v.1.0-SNAPSHOT

**Comment by danymill** [comment]
fixed on UI from v. `1.35.RC1`

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.35.RC3 server: 4.1.88.RC6 client: 4.1.65.
