### ISSUE TITLE
"Mark as reviewed"button is shifted when window has scroll

### ISSUE THREAD

**Issue by lmikhadyuk** [qaprosoft/zafira#2068]
**Steps to reproduce**
1. Login to Zafira
2. Open test runs tab
3. Click on 3 dots on test run
4. Select Mark as reviewed
5. Enter text (to be able to scroll this text)

**Actual behavior**
"Mark as reviewed" button is shifted
<img width="2041" alt="Screen Shot 2020-02-25 at 17 11 22" src="https://user-images.githubusercontent.com/56070333/75255273-b5adf480-57f2-11ea-9271-aa1b3a367537.png">

**Environment**
ui: 1.31-SNAPSHOT
server: 4.1.88.RC7
client: 4.1.65

**Comment by MitskevichVS** [comment]
fixed from UI version 1.377-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.33-SNAPSHOT server: 1.565-SNAPSHOT client: 1.0-SNAPSHOT.
