### ISSUE TITLE
"Link issue" option should present for all Faild bugs

### ISSUE THREAD

**Issue by okamara** [qaprosoft/zafira#2070]
**Description**
"Link issue" option is not present for Bugs that user made Failed from Passed

**Steps to reproduce**
[Make sure to specify user role used to log in to Zafira]
Below are the steps to reproduce the behavior:
1. Go to Test runs and open any test run results
2. Click on 'More option" near a test case with Passed status
3. Set result Failed
4. Click on 'More option" near a test case to link issue

**Actual behavior**
"Link issue" option is not present 

**Expected behavior (if known)**
"Link issue" option should present for all Faild bugs

**Environment**
ui v.1.35.RC3 | server v.4.1.88.RC6 | client v.4.1.65

<img width="1357" alt="Screen Shot 2020-02-26 at 2 54 48 PM" src="https://user-images.githubusercontent.com/32964663/75343066-b0ab7c80-58a8-11ea-9451-098a649ecdff.png">

Expected:
<img width="1364" alt="Screen Shot 2020-02-26 at 2 54 58 PM" src="https://user-images.githubusercontent.com/32964663/75343087-bbfea800-58a8-11ea-8d76-522202d8e8f6.png">

**Comment by lmikhadyuk** [comment]
It's a feature, not a bug.
