### ISSUE TITLE
Timeout/limit of test execution handling by Carina.

### ISSUE THREAD

**Issue by akupriyanov** [qaprosoft/zafira#245]
What about new feature in Carina/Zafira and stopping test execution if it exceeds defined timeout parameter?
Right now we control it by Jenkins Abort plugin. But when Jenkins aborts execution we loss eTAF_Report and part of logs, it's not always clear what happened and this feature is not available for local run.
Proposing any kind of max_execution_time parameter (0 by default) and carefully stop TestNG execution in case this timeout reached.

**Comment by hursevich** [comment]
This is definitely non-zafira task, reporting tool should not control execution flow. We need to setup test-layer timeouts by testng http://testng.org/doc/documentation-main.html#parallel-running
