### ISSUE TITLE
Return the opportunity to integrate with GitHub Issues

### ISSUE THREAD

**Issue by siarhei-babich** [qaprosoft/zafira#346]
Earlier JIRA integration feature worked for the purpose.
But after Jira ID text field validation was added (regexp \w+-\d+), GitHub integration became unsupported w/o access to DB.

Possible solutions:
1) add GitHub integration feature (labor-intensive)
2) remove Jira ID regexp validation (quick fix)
3) add possibility for a user to re-set a the default validation regexp, if needed (quick fix)

Reproducible in Zafira on 52.6.39.54 (no info about the version detected).

Example:

JIRA_URL: https://github.com/[REPO_NAME]/[PROJECT _NAME]/issues
Issue: 1
Result: I am not able to add a know issue with ID = 1.

**Comment by tsvrko** [comment]
Fixed https://github.com/qaprosoft/zafira/pull/461
