### ISSUE TITLE
id's from TestRail is not displayed

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#387]
For several tests id's from TestRail is not displayed, screenshot is attached.
repro steps:
1) open zafira, open Test Runs
2) select some tests, c click by "..."
Expected: Log, Demo and id's from TestRail are displayed
Actual:  Log, Demo are displayed

![screen shot 2017-11-29 at 12 08 51](https://user-images.githubusercontent.com/3008517/33367096-66fe16b8-d4fe-11e7-9249-740ca330469a.png)

**Comment by hursevich** [comment]
resolved
