### ISSUE TITLE
improve zafira integration points for qps-infra docker container

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#404]
I'd like to have workable integrations zafira items right after starting qps-infra containers.
As I see we can automatically enable integrations for:
jenkins
rabbitmq
email
...

**Comment by hursevich** [comment]
1. See new integrations.env file https://github.com/qaprosoft/zafira/blob/master/integrations.env
2. Include reference to variable in postgres component https://github.com/qaprosoft/zafira/blob/master/docker-compose.yml#L11
3. To inject variables into postgres on startup - make sure appropriate ENABLED flag equals true (it only injects if integration enabled https://github.com/qaprosoft/zafira/blob/master/database/zafira-init.sh#L12)
