### ISSUE TITLE
Not all tests are running in jenkins from testNG suites

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#458]
Not all tests are running in jenkins from testNG suites, and jenkins report, zafira report don't have all tests (pass, fails, skips)

**Comment by vdelendik** [comment]
please explain why tests on CI do not use testNG suite xml files. That's the only place where we recommend to declare ZafiraListener...

**Comment by vdelendik** [comment]
can't reproduce. feel free to open new issue with details
