### ISSUE TITLE
Add possibility to add comments in each test and execution.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#462]
Sometimes we have to show and keep actual results with failures (for example if failure happen only on some specific device) and do not mark as passed or add known issue. And it will be useful if we can add some comments and details for failure or skipped test (may be it can be useful for passed too). And the must thing should be showing this comments in sent report.

**Comment by tsvrko** [comment]
Done https://github.com/qaprosoft/zafira/commit/46622192d5a1b568e49e5d9cc7727a58dffdca49
