### ISSUE TITLE
Zafira displays incorrect count of tests in status "in progress"

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#464]
Zafira displays incorrect count of tests in status "in progress", I attached screen shot, we can see 10 test in status in progress, this impossible, because I started against 6 threads, and we have only 6 simulators in cloud in this moment
This issue was opened early
https://github.com/qaprosoft/zafira/issues/293

![screen shot 2018-01-09 at 21 42 14](https://user-images.githubusercontent.com/3008517/34737106-2ca49ee4-f586-11e7-9f40-1d81b509a761.png)

**Comment by vdelendik** [comment]
fixed
