### ISSUE TITLE
Add possibility to send multiple test results to required emails

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#467]
Often I have to send results for specific runs for some customers after manual checking and reviewing. And it is really annoying to do it one by one. 
Solution required with selecting multiple runs: 
![image](https://user-images.githubusercontent.com/4455896/34801111-201d56de-f667-11e7-915b-c7caeba965f5.png)

And adding feature similar to sending one run in burger button:
![image](https://user-images.githubusercontent.com/4455896/34801155-590d361c-f667-11e7-95f8-eba21e3d9a68.png)
(May be export can be added in similar way) 
And send all these selected results to required contacts.

**Comment by hursevich** [comment]
done
