### ISSUE TITLE
Zafira has tests with status "in progress", after job failed

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/zafira#471]
iOS run, simulators were down, selenium session could not be created , after several times job failed, but zafira displayed incorrect statics about tests, zafira had tests "in progress"
https://ua.qaprosoft.com/zafira/#!/tests/runs/9933

https://ua.qaprosoft.com/jenkins/job/Automation/job/MMF-iOS-Minimal-Acceptance/251/console

![screen shot 2018-01-16 at 09 25 03](https://user-images.githubusercontent.com/3008517/34974640-3a67e612-fa9f-11e7-9898-703ae7ea202e.png)

**Comment by hursevich** [comment]
- fixed and will be released ASAP
