### ISSUE TITLE
AI/Algorithm: integrate suggested fixes for each debug failure

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#485]
for original use-case take a look to https://github.com/qaprosoft/zafira/issues/483 where we can provide possibility to start debug process in one click and request human analysis when everything is ready for debugging.
In scope of this ticket I'd like to investigate and deliver service which analyze old fixes by humans and suggest to apply the similar based on defect/error message etc for current project

**Comment by hursevich** [comment]
Looks like debug feature is too complex for the reporting tool, let's not invest time into rarely used features.
