### ISSUE TITLE
Incorrect mappint in test runs

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#494]
When I open logs from within automation report on Zafira, system provides me with logs for incorrect test and may give an incorrect link to test case from TestRails automation report. See the attached videos

Links for anyone at Qaprosoft:
https://drive.google.com/file/d/1edNPS_bwdieipI-VBOSFAm57ieB0ccxz/view?usp=sharing
https://drive.google.com/file/d/1FRXMm9hN5GUaDF7ujLDtah7SkRgdFA4D/view?usp=sharing

**Comment by SergeiZagriychuk** [comment]
not repro
