### ISSUE TITLE
Incorrect description of existing known issue

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#527]
**Preconditions:**
Mark at least one failed test with known issue (using existing JIRA ticket).

**Steps to repro:**
1. Find additional failed test scenario
2. Click on "Mark as known issue"

Expected result: User is able to mark this test with existing JIRA ticket (with correct description)
Actual result: Incorrect description of existing issue.
![wrongdescription1](https://user-images.githubusercontent.com/21850997/36169823-6db07266-110e-11e8-8fc7-1ac0a2d6c9b9.png)
![wrongdescription2](https://user-images.githubusercontent.com/21850997/36169824-6dd17e16-110e-11e8-8ca3-52adcfa2d196.png)

**Comment by Boniara** [comment]
cannot reproduce
