### ISSUE TITLE
Incorrect amount of known issues for testrun

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/zafira#533]
Preconditions:
Open any testrun with failed test

Steps:
Click on "Mark as known issue"
Choose any option: select either existing or create new JIRA ticket

Defect: The amount of known issues is bigger than expected
![failurescountissue](https://user-images.githubusercontent.com/21850997/36248902-16f65570-124a-11e8-859c-59637df2fabb.png)

**Comment by Boniara** [comment]
cannot reproduce
