### ISSUE TITLE
Add possibility to download required builds directly from Zafira

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#550]
Add separate permission and make possible to download required build from Zafira test run view. 
Where we have apk or ipa build names (useful for Android and iOS manually test failure re-checking).
For now should work only if builds will be stored in Amazon cloud and there will be configured Amazon integration.

**Comment by vdelendik** [comment]
Discussed feature and agreed that much easier it will be to share default /opt/apk to zafira container as well and provide for downloading actual physical file from /opt/apk/<app_version> of course if it exists as manual cleanup is possible.
