### ISSUE TITLE
Add test_suites.name in Weekly_view

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#555]
Add test_suites.name in Weekly_view (and probably in other views as well) for adding status of different suites execution in widget.

**Comment by vdelendik** [comment]
please add as separate property to all our views except total_view as I see now.
test_suites.name as suite_name

Changes should be incorporated into the default db-* queries and 065 and 066 alter scripts

**Comment by tsvrko** [comment]
added #557
