### ISSUE TITLE
Add feature: have a possibility to assign a known issue to skipped test

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#567]
Let's imagine, that i have some logic in BeforeTest method (like registration) and somewhere there is a bug that doesn't let me pass to the desired location within an application from which i would like to start my test logic. Thus, basically, this test is skipped due to some known issue and i want to have a possibility to mark such a test appropriately.

Simultaneously, i think that such skipped test should stay skipped.

**Comment by Boniara** [comment]
there isn't a logic to assign known issue to skipped test

**Comment by maksimsarychau** [comment]
Another proposition - to add possibility mark skipped tests as Failed (and then we can add Known issues there). Currently we can just mark them as Passed.

**Comment by Boniara** [comment]
We don't think that it is a good idea. We follow up on this proposition later.
