### ISSUE TITLE
ZafiraClient: make ci_build_cause as optional

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#579]
it seems like if we don't provide this argument we couldn't register test run successfully.
so default value for it should be specified as
ci_build_cause=MANUALTRIGGER

**Comment by hursevich** [comment]
Looks like this case is controlled here https://github.com/qaprosoft/zafira/blob/master/sources/zafira-client/src/main/java/com/qaprosoft/zafira/listener/ZafiraListener.java#L600
