### ISSUE TITLE
Can't perform rerun in case I have only passed and skipped tests (no fails)

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#587]
Issue: when I perform a rerun (though Zafira) of a test run which has only passed and skipped tests within, no even one test is started, whole test run is skipped.

We use driver_mode=method_mode

**Comment by vdelendik** [comment]
@tsvrko please review how do we recalculate need_rerun flag for skipped only tests

**Comment by tsvrko** [comment]
not reproduced
