### ISSUE TITLE
Cant install zafira with docker.

### ISSUE THREAD

**Issue by boyfromearth** [qaprosoft/zafira#588]
Hello. I'm trying to follow steps to install zafira but docker can't find file integrations.env. Is there additional step required?

**Comment by vdelendik** [comment]
extra argument were moved to integrations.env file
please download it as well:
curl https://raw.githubusercontent.com/qaprosoft/zafira/master/integrations.env -o integrations.env

readme will be updated as well.
thanks for the ticket:+1:

**Comment by boyfromearth** [comment]
thank you for quick response!! Спасибо Вадим!! Я пытаюсь продвинуть Ваш тул на новом рабочем месте!!
