### ISSUE TITLE
Database can't start during simple installation

### ISSUE THREAD

**Issue by boyfromearth** [qaprosoft/zafira#589]
Docker can't spin up Zafira. Looks like some files have wrong ownership on postgres image:
waiting for server to start....FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

root@2523388bc382:/var/lib/postgresql# ls -l
drwxrwxrwx 2 postgres postgres 4096 Mar 15 20:05 data
root@2523388bc382:/var/lib/postgresql#

**Comment by boyfromearth** [comment]
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in URL [jar:file:/usr/local/tomcat/webapps/zafira-ws/WEB-INF/lib/zafira-dbaccess-2.0.jar!/com/qaprosoft/zafira/dbaccess/dao/mappers/UserMapper.xml]
### The error may involve com.qaprosoft.zafira.dbaccess.dao.mysql.UserMapper.getUserByUserName
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!

**Comment by boyfromearth** [comment]
I ggolead a bit and found that issue was fixed in postgres v10
https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/26
See comment from joneslee85

**Comment by vdelendik** [comment]
please attach full log files into this ticket for
docker logs qpsinfra_db_1 > pg_console.log
docker logs qpsinfra_zafira_1 > zafira_console.log

**Comment by boyfromearth** [comment]
[pg_console.log](https://github.com/qaprosoft/zafira/files/1817560/pg_console.log)
[zafira_console.log](https://github.com/qaprosoft/zafira/files/1817561/zafira_console.log)

here are the logs

**Comment by boyfromearth** [comment]
unfortunately, the way you proposed with placing files in database and database/sql folders didn't work!! Same error happened. 
db_1        | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

**Comment by hursevich** [comment]
Please read article https://denibertovic.com/posts/handling-permissions-with-docker-volumes/ that describes permission settings for docker volumes. Initial problem is that UID of docker user and owner of the folder you are sharing is different.

**Comment by boyfromearth** [comment]
i'm using windows 10

**Comment by hursevich** [comment]
Unfortunately we are not using Windows based laptops, I will try to find Windows machine and test deployment process. You may also review some stackoverflow articles and create additional volume https://stackoverflow.com/questions/33126271/how-to-use-volume-option-with-docker-toolbox-on-windows

**Comment by boyfromearth** [comment]
So, is there a chance to use zafira out of Carina scope? what classes should be pulled and from where is yes?

**Comment by vdelendik** [comment]
on Win 10 I suppose postgres can be installed as dedicated DB server. It could resolve all these configuration failures.

As about direct using of zafira I believe steps should be:
1. add dependency to zafira client to your project
        <dependency>
            <groupId>com.qaprosoft</groupId>
            <artifactId>zafira-client</artifactId>
            <version>3.0.35</version>
        </dependency>
2. register appropriate listener globally on pom.xml level like in this commented piece of code for maven-surefire-plugin:
https://github.com/qaprosoft/carina-demo/blob/master/pom.xml 

or
register on testng suite file level:
https://github.com/qaprosoft/carina-demo/blob/master/src/test/resources/testng_suites/api.xml

3. implement com.qaprosoft.zafira.config.IConfigurator interface to let Zafira know how do you want to register tests.
Example can be found here:
https://github.com/qaprosoft/carina/blob/87dbd0a1d7d742cf19cc1547eb0186b90fa6baf6/carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java

4. put into resources zafira.properties file with valid url and token
https://github.com/qaprosoft/carina-demo/blob/master/src/main/resources/zafira.properties

**Comment by unickq** [comment]
Zafira is still can't be launched on Win10. 
Why is this issue closed?
