### ISSUE TITLE
introduce new test run status: scheduled

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#591]
to track regression status in run-time and be able to show % of the planned regression new feature is needed:
1. new test run status - SCHEDULED
2. new end-point for schedule/add to CI queue new job/test run
-> it should register new test run with status SCHEDULE and approx number of expected tests based on historical results (last 10 execution for current repo/suite/branch)

3. later test run should first of all look for scheduled test run and reuse it test_run_id for registration

**Comment by tsvrko** [comment]
introduced in zafira 3.1.10 #726 #722
