### ISSUE TITLE
Improve rerun logic

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/zafira#597]
An issue occurs in rerun logic in the next case:
1. Define test tags in xml suite which use the same test class but different parameters.
![xml_example](https://user-images.githubusercontent.com/16190512/37704778-e390d4c2-2d0a-11e8-8a7b-a7afbac9936c.png)

Test method example:

![test_example](https://user-images.githubusercontent.com/16190512/37704793-f28d82f4-2d0a-11e8-9212-ce63ce89dd70.png)

2. Run this suite on jenkins/zafira.
3. Do rerun failures. 

Actual result : the tests won't be rerun.

**Comment by hursevich** [comment]
Should be fixed in latest releases.
