### ISSUE TITLE
Add possibility to attach closed issues from TestRail as Known Issue without reopen them 

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#609]
If we have stable TestRail integration, Zafira check bugs status.
Here we have only open bugs available (even with some duplicates):
![image](https://user-images.githubusercontent.com/4455896/38304675-828da50a-380a-11e8-93f0-7fc4bcf3a0a4.png)
It will be good to have closed bugs assigned to this tests (with green background) for selection as well. May be in separate extendable div. 
Will be useful if bug was already closed on Master branch, but still available in some feature branch.

**Comment by hursevich** [comment]
Looks like this ticket is dedicated to Jira integration, this logic was globally refactored in the latest releases.
