### ISSUE TITLE
Secondary owner statistic is incorrect 

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/zafira#640]
Steps:
1. Create any test with two owners : @MethodOwner(owner = "owner1", secondaryOwner = "owner2")
2. Check zafira results.

Actual results: 
- nightly dashboard statistic is incorrect. The tests are not populated for secondary owner.

**Comment by vdelendik** [comment]
We have to refactor ownership removing 2ry owner at all but be able to register primary owner filtered by os/config/platform (?)
For example:
    @MethodOwner(owner = "ab", platform = "android")
    @MethodOwner(owner = "cd", platform="ios")
    @MethodOwner(owner = "ef", platform="desktop")

and based on existing platform in R.CONFIG register test run for appropriate owner.
Also change test_case table generating complex primary id with
test_class, test_method, owner_id

**Comment by vdelendik** [comment]
secondary owner feature is going to be removed. won't fix
