### ISSUE TITLE
Create button is disabled on Edit known issue page

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#647]
Steps: 
1. Open any run with failed tests
2. Tap Edit known issue on failed test
3. Select jira ticket
Actual result: Ticket description is loading from jira -> Create button is disabled
Expected: Create button is enabled

DEMO: https://www.dropbox.com/s/27dq5bv723oxeqh/ice_video_20180424-190900.webm?dl=0

cc. @hursevich, @vdelendik

**Comment by Boniara** [comment]
@kdaroshka ,  it's not a bug. Closed tickets couldn't be attached.
