### ISSUE TITLE
User is taken to the top of zafira test run after marking test with result

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#714]
Environment: Chrome, Mozilla,
cleared cache and cookies
Win7, Win10

Description: anytime I mark any test with result (passed or failed). I am taken to the top of test run.

steps: 
1. Open any test run with failed/skipped tests
2. Select any failed test
3. Click Test details button
4. Select `passed` result for this test
5. Click Save
6. Click `X` button to close details screen
Actual result: user is taken to the top view of the screen
Expected result: User should stay in the same position as he was before marking test (middle of the screen or bottom of the screen). Test run page should not take user to the top view after user marks test with result

DEMO: https://www.dropbox.com/s/briiedjhevn007s/ice_video_20180511-181709.webm?dl=0

cc. @vdelendik, @hursevich

**Comment by Boniara** [comment]
was fixed
