### ISSUE TITLE
[Improvement] Visually separate screenshots for  1st test and retry-attempt

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#751]
Let's imagine, that we conduct a test run with retry_count=1.
In case some test has failed, and was restarted after, we see screenshots that are displayed as one heap/sequence.

I suggest to separate them for both attempts visually. Like:
Initial test:
{some screenshots}

Restarted test:
{some screenshots}

**Comment by Litsvin** [comment]
OR 
what about precessing on-fail screenshot in order to paint it in red color?

**Comment by vdelendik** [comment]
obsolete
