### ISSUE TITLE
queued tests have old elapsed time

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#752]
Zafira: 3.1.1.13.
for each queued test we should reset elapsed time during copying tests from previously testrun
![queued-elapsed-tests](https://user-images.githubusercontent.com/4551455/40396260-b01c0d0e-5e34-11e8-8bd7-3d2ab890305d.png)

**Comment by tsvrko** [comment]
now time is not displayed 944a2c3b1958d294b2938efd98c71454847ac48f
