### ISSUE TITLE
smart rebuild end-point on zafira level needed

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#754]
To be able to rebuild some milestones, jobs etc the best tool is Zafira.
Please create end-point only which allow to rebuild list of jobs based on custom rules:
1. By repo
2. By owner
3. By error hashcode
4. by parent job/build
5. by percent of the fail test inside job

As extra boolean step I want to provide:
rerun_failures as true/false

**Comment by tsvrko** [comment]
implemented https://github.com/qaprosoft/zafira/pull/789
