### ISSUE TITLE
aborted and queued jobs doesn't have timing details

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#773]
3.1.16
We have only Aborted and Queued... It is expected to have
Queued 2 minutes ago
Aborted 5 hours ago etc

**Comment by vdelendik** [comment]
issue is reproduced in the case when test wasn't even started on CI i.e. when compilation failure or someone aborted from CI queue

**Comment by tsvrko** [comment]
Fixed  #775
