### ISSUE TITLE
Add possibility to select date range for weekly/monthly report.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#786]
Sometimes if you missed EOW or EOM you can't send a weekly or monthly report. It will be useful to add the possibility of selecting the date range for MONTHLY_VIEW and WEEKLY_VIEW

**Comment by vdelendik** [comment]
new widgets generator allow to update period as you wish starting from 24 hours till total history.
Moreover some of the charts automatically choose group by period to show data correctly.
3.4.51+
