### ISSUE TITLE
Work item buttons don't function

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#800]
Environment: Chrome (66.0.3359.181), Firefox (60.0.1)

Steps:
1. Open any test run
2. Click on work item button
Actual result: Work item button doesn't work
Expected: Work item button should take user to test details window

Work item buttons: ![ice_screenshot_20180608-171551](https://user-images.githubusercontent.com/24683436/41163190-af435b08-6b40-11e8-9b7d-228d5ecbda1e.png)

cc. @vdelendik @hursevich

**Comment by Boniara** [comment]
not reproducible
