### ISSUE TITLE
remove zafira_report_emails property and related functionality

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#817]
As only qps-pipeline can notify owners we can remove above property and apropriate code from zafira client.

https://github.com/qaprosoft/qps-pipeline/issues/30

**Comment by tsvrko** [comment]
implemented in https://github.com/qaprosoft/zafira/tree/demo

**Comment by tsvrko** [comment]
closed https://github.com/qaprosoft/zafira/pull/878
