### ISSUE TITLE
Blocker label has not disappeared after test was passed

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/zafira#836]
During some test runs there was a test signed as known issue. After the test had been passed it still was signed with blocker label, but wasn't signed as known issue. After test run had been marked as reviewed, blocker label appeared next to the test run name.

https://ua.qaprosoft.com/zafira/#!/tests/runs/12931

**Comment by Boniara** [comment]
@deNatallia 
It is not a Zafira bug. Your test was marked as passed manually. Please, resolve this issue in your team.
Follow up on this issue as well. If it is reproducible you can reopen this one to improve our project. Thanks.
