### ISSUE TITLE
UI is broken in redesign branch

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/zafira#837]
When you a scroll down and trying to open menu from header meny - header disappeares and page becomes non-scrollable. Also on dashboard page when you scroll to the widgets management list - context menu available by 3 dots not working.

<img width="1606" alt="screen shot 2018-06-24 at 10 06 10 pm" src="https://user-images.githubusercontent.com/1182755/41822593-d8284b70-77fa-11e8-8c51-1d66a0be9932.png">

**Comment by Boniara** [comment]
done
