### ISSUE TITLE
Need possibility to choose link onto concrete log line

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#864]
Need the similar functionality as permalink in Github: https://github.com/qaprosoft/zafira/blob/4ba2edb9d98623f7e191132e031f0628a0b216e7/docker-compose.yml#L27

So <zafira>/#!/tests/runs/id/info/id should be able to copy and share such link as well it provides possibility to share direct url to logs and later to screenshots as well

**Comment by Boniara** [comment]
done
