### ISSUE TITLE
Register Jira "known issues" basing on DataProvider name, not just method name.

### ISSUE THREAD

**Issue by akupriyanov** [qaprosoft/zafira#88]
If you have 1 test method and it runs 10 different tests basing on dataprovider and one of tests failed - you can set "known issue" via Zafira. But once the second test will be failed - this known issue will be automatically set that is not correct.
It should work in similar way like you set JiraTicket exactly in your .xls for appropriate test.

**Comment by hursevich** [comment]
- unfortunately it is not possible to implement by design, known issue is assigned to test case id, all the tests from dataprovider will refer to the same test case id
