### ISSUE TITLE
Unable to collapse video if expanded live video automatically switched to the sate with recorded player

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#881]
steps:
1. launch any UI test
2. open "watch" view for testmethod and expand live video player
3. wait until test is finished and new player is displayed
-> recorded player is displayed using the same size as for expanded live video player. It can't be collapsed anymore
It seems like we should automatically switch to normal view as only testmethod is finished

![collapsed-but-huge-state](https://user-images.githubusercontent.com/4551455/42289539-c825f3a0-7fc8-11e8-95b6-f1f8f4c2b1c4.png)

**Comment by Boniara** [comment]
done
