### ISSUE TITLE
Stability -> STABILITY TREND (%) widget has invalid min y value

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#882]
As there is not below declaration for axes stability widget is shown incorrectly. 30-50% pass rate looks to small:
"axes": {
        "x": {
            "key": "TESTED_AT",
            "type": "date"
        },
        **"y": {
            "min": "0"
        }**
    }

we have to adjust this widget and review all default widgets with the similar logic when up to 100% chart is displayed. For all of them y min=0 should be added into the model

**Comment by tsvrko** [comment]
reviewed #890
