### ISSUE TITLE
Can't perform rerun using Zafira if I need to kick off a test run from my fork

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#894]
server v.3.1.25 | client v.3.0.40
https://host/jenkins/job/Automation/job/..-Android-Minimal-Acceptance/156/console

**Comment by Litsvin** [comment]
can't start the first test run also

**Comment by vdelendik** [comment]
it should be retested in new qps-pipeline

**Comment by vdelendik** [comment]
feature should be available
