### ISSUE TITLE
Dashboard nightly total peicharts do not display correct number of tests

### ISSUE THREAD

**Issue by kdaroshka** [qaprosoft/zafira#905]
Env: Win7, Chrome, Firefox

Description: 
Zafira doesn't show results of web tests.
I can see correct data in JIRA Tickets table, but Nightly total pies do not include those tests (WEB). It is showing only tests from mobile runs.

**Comment by vdelendik** [comment]
zafira_project is declared incorrectly as result project filter doesn't include those runs. not a bug but configuration issue in test automation scripts
