### ISSUE TITLE
[Improvement] Is it possible to add success rate in % to zafira's test report

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/zafira#907]
pass | skipped | failed | queued | in progress
isn't handy enough to estimate success rate

**Comment by tsvrko** [comment]
alpready implemented

**Comment by tsvrko** [comment]
![image](https://user-images.githubusercontent.com/23284071/68870043-3ac14200-070b-11ea-99f4-18a45feb1d3c.png)
