### ISSUE TITLE
export Zafira report after test execution could fail due to the expired access/refresh token

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#978]
Sometime due to the huge queue real test execution could happen in several hours after registration. As result we successfully register it as queued but later during the export we have 401 error.

So we have to try/catch such option and re-enable token before export/abort etc if needed

**Comment by vdelendik** [comment]
in this particular case job run time was 5 hours.

**Comment by tsvrko** [comment]
done https://github.com/qaprosoft/qps-pipeline/pull/116
